SELECT
    ccpversion,
    maprojid,
    magencyacro AS magenacro,
    magency,
    magencyname AS magenname,
    description AS descript,
    projectid,
    mindate,
    maxdate,
    typecategory AS typecat,
    plannedcommit_ccnonexempt AS pcccnonex,
    plannedcommit_ccexempt AS pcccex,
    plannedcommit_citycost AS pccc,
    plannedcommit_nccstate AS pcnccstate,
    plannedcommit_nccfederal AS pcnccfed,
    plannedcommit_nccother AS pcnccother,
    plannedcommit_noncitycost AS pcncc,
    plannedcommit_total AS pctotal,
    adopt_ccnonexempt AS adccnonex,
    adopt_ccexempt AS adccex,
    adopt_citycost AS adcc,
    adopt_nccstate AS adnccstate,
    adopt_nccfederal AS adnccfed,
    adopt_nccother AS adnccother,
    adopt_noncitycost AS adncc,
    adopt_total AS adtotal,
    allocate_ccnonexempt AS alccnonex,
    allocate_ccexempt AS alccex,
    allocate_citycost AS alcc,
    allocate_nccstate AS alnccstate,
    allocate_nccfederal AS alnccfed,
    allocate_nccother AS alnccother,
    allocate_noncitycost AS alncc,
    allocate_total AS altotal,
    commit_ccnonexempt AS coccnonex,
    commit_ccexempt AS coccex,
    commit_citycost AS cocc,
    commit_nccstate AS conccstate,
    commit_nccfederal AS conccfed,
    commit_nccother AS conccother,
    commit_noncitycost AS concc,
    commit_total AS cototal,
    spent_ccnonexempt AS spccnonex,
    spent_ccexempt AS spccex,
    spent_citycost AS spcc,
    spent_nccstate AS spnccstate,
    spent_nccfederal AS spnccfed,
    spent_nccother AS spnccother,
    spent_noncitycost AS spncc,
    spent_total AS sptotal,
    spent_total_checkbooknyc AS sptotalcb,
    geom
FROM {{ ref('cpdb_projects_geom') }}
