# The following was generated from the call to the Socrata Publishing API
# for the `MIH Test` dataset, then some light variable swapping for testing
# purposes.

# from dcpy.connectors.socrata import publish
# ds = publish.Dataset(four_four="p6cc-cxkc")

MIH_FOUR_FOUR = "p6cc-cxkc"
MIH_ATTACHMENT_NAME = "nycmih_metadata.pdf"

mih_metadata = {
    "id": MIH_FOUR_FOUR,
    "name": "MIH Test",
    "assetType": "dataset",
    "attribution": "DCP",
    "averageRating": 0,
    "category": "Housing & Development",
    "createdAt": 1697124045,
    "description": "Description for Mandatory Inclusionary Housing",
    "displayType": "table",
    "downloadCount": 3,
    "hideFromCatalog": False,
    "hideFromDataJson": False,
    "licenseId": "ODC_BY",
    "newBackend": True,
    "numberOfComments": 0,
    "oid": 40063981,
    "provenance": "official",
    "publicationAppendEnabled": False,
    "publicationDate": 1697492307,
    "publicationGroup": 19324528,
    "publicationStage": "published",
    "resourceName": "MIH_TEST",
    "rowsUpdatedAt": 1702529304,
    "rowsUpdatedBy": "iqqb-gm94",
    "tableId": 19324528,
    "totalTimesRated": 0,
    "viewCount": 104,
    "viewLastModified": 1709592859,
    "viewType": "tabular",
    "approvals": [
        {
            "state": "submittable",
            "submissionObject": "public_audience_request",
            "submissionOutcome": "change_audience",
            "targetAudience": "public",
            "workflowId": 2285,
            "submissionDetails": {"permissionType": "READ"},
        }
    ],
    "clientContext": {"clientContextVariables": [], "inheritedVariables": {}},
    "columns": [
        {
            "id": 583119021,
            "name": "the_geom",
            "dataTypeName": "multipolygon",
            "description": "Geometry type, changed",
            "fieldName": "the_geom",
            "position": 1,
            "renderTypeName": "multipolygon",
            "tableColumnId": 149304422,
            "format": {},
        },
        {
            "id": 583119022,
            "name": "Boro",
            "dataTypeName": "text",
            "description": "The NYC Borough where the Mandatory Inclusionary Housing (MIH) area is mapped. The boro code is a single digit identifier, indicating a particular borough (1 = Manhattan, 2 = Bronx, 3 = Brooklyn, 4 = Queens, 5 = Staten Island).",
            "fieldName": "boro",
            "position": 2,
            "renderTypeName": "text",
            "tableColumnId": 149304423,
            "cachedContents": {
                "non_null": "197",
                "largest": "5",
                "null": "0",
                "top": [
                    {"item": "3", "count": "80"},
                    {"item": "4", "count": "45"},
                    {"item": "2", "count": "38"},
                    {"item": "1", "count": "20"},
                    {"item": "5", "count": "5"},
                ],
                "smallest": "1",
                "count": "197",
                "cardinality": "5",
            },
            "format": {},
        },
        {
            "id": 583119023,
            "name": "Status",
            "dataTypeName": "text",
            "description": "Status of the ULURP text amendment application (Adopted = final approval, Pipeline = awaiting approval)",
            "fieldName": "status",
            "position": 3,
            "renderTypeName": "text",
            "tableColumnId": 149304424,
            "cachedContents": {
                "non_null": "197",
                "largest": "Adopted",
                "null": "0",
                "top": [
                    {"item": "Adopted", "count": "196"},
                    {"item": "Adoped", "count": "1"},
                ],
                "smallest": "Adoped",
                "count": "197",
                "cardinality": "2",
            },
            "format": {},
        },
        {
            "id": 583119024,
            "name": "Project Name",
            "dataTypeName": "text",
            "description": "Project Name of the Mandatory Inclusionary Housing (MIH) area.",
            "fieldName": "projectnam",
            "position": 4,
            "renderTypeName": "text",
            "tableColumnId": 149304425,
            "cachedContents": {
                "non_null": "197",
                "largest": "Willow Avenue Rezonng",
                "null": "0",
                "top": [
                    {"item": "Jerome Avenue Rezoning", "count": "2"},
                    {"item": "Queens Blvd MIH Text Amendment", "count": "2"},
                    {"item": "Special Bay Street Corridor District", "count": "2"},
                    {"item": "Willow Avenue Rezonng", "count": "1"},
                    {"item": "62-04 Roosevelt Avenue", "count": "1"},
                    {"item": "1930 Adee Avenue Rezoning", "count": "1"},
                    {"item": "98-81 Queens Boulevard Rezoning", "count": "1"},
                    {"item": "Pfizer Sites Rezoning", "count": "1"},
                    {"item": "57 Canton Place", "count": "1"},
                    {"item": "587 Bergen Street Rezoning", "count": "1"},
                    {"item": "103 Lee Avenue", "count": "1"},
                    {"item": "SoHo/NoHo Neighborhood Plan", "count": "1"},
                    {"item": "2 Howard Avenue", "count": "1"},
                    {"item": "126th Street Bus Depot", "count": "1"},
                    {"item": "Lower Concourse North Rezoning", "count": "1"},
                    {"item": "11-14 35th Avenue", "count": "1"},
                    {"item": "Downtown Far Rockaway Development Plan", "count": "1"},
                    {"item": "1776 Eastchester Road", "count": "1"},
                    {"item": "431 Concord Avenue", "count": "1"},
                    {"item": "New York City Borough - Based Jail System", "count": "1"},
                ],
                "smallest": "1010 Pacific Street",
                "count": "197",
                "cardinality": "194",
            },
            "format": {},
        },
        {
            "id": 583119025,
            "name": "Date Adopted",
            "dataTypeName": "calendar_date",
            "description": "The date the ULURP text amendment application was adopted.",
            "fieldName": "dateadopte",
            "position": 5,
            "renderTypeName": "calendar_date",
            "tableColumnId": 149304426,
            "cachedContents": {
                "non_null": "197",
                "largest": "2023-09-28T00:00:00.000",
                "null": "0",
                "top": [
                    {"item": "2021-11-23T00:00:00.000", "count": "7"},
                    {"item": "2022-04-28T00:00:00.000", "count": "6"},
                    {"item": "2018-03-22T00:00:00.000", "count": "5"},
                    {"item": "2021-10-21T00:00:00.000", "count": "5"},
                    {"item": "2018-10-31T00:00:00.000", "count": "4"},
                    {"item": "2017-11-30T00:00:00.000", "count": "4"},
                    {"item": "2019-10-17T00:00:00.000", "count": "4"},
                    {"item": "2018-09-26T00:00:00.000", "count": "4"},
                    {"item": "2019-05-08T00:00:00.000", "count": "4"},
                    {"item": "2017-10-17T00:00:00.000", "count": "4"},
                    {"item": "2022-07-14T00:00:00.000", "count": "4"},
                    {"item": "2019-06-26T00:00:00.000", "count": "4"},
                    {"item": "2021-05-27T00:00:00.000", "count": "4"},
                    {"item": "2021-12-15T00:00:00.000", "count": "4"},
                    {"item": "2017-05-24T00:00:00.000", "count": "3"},
                    {"item": "2021-03-18T00:00:00.000", "count": "3"},
                    {"item": "2016-11-29T00:00:00.000", "count": "3"},
                    {"item": "2017-07-20T00:00:00.000", "count": "3"},
                    {"item": "2020-04-22T00:00:00.000", "count": "3"},
                    {"item": "2017-09-07T00:00:00.000", "count": "3"},
                ],
                "smallest": "2016-04-20T00:00:00.000",
                "count": "197",
                "cardinality": "91",
            },
            "format": {},
        },
        {
            "id": 583119026,
            "name": "ZR_ULURP Number",
            "dataTypeName": "text",
            "description": "The ULURP number of the ULURP text amendment application.",
            "fieldName": "zr_ulurpno",
            "position": 6,
            "renderTypeName": "text",
            "tableColumnId": 149304427,
            "cachedContents": {
                "non_null": "197",
                "largest": "N230292ZRX",
                "null": "0",
                "top": [
                    {"item": "190352ZRQ", "count": "2"},
                    {"item": "180051AZMX", "count": "2"},
                    {"item": "160036ZRK", "count": "2"},
                    {"item": "160222ZRK", "count": "2"},
                    {"item": "190114AZRR", "count": "2"},
                    {"item": "210322ZRX", "count": "1"},
                    {"item": "180122ZRX", "count": "1"},
                    {"item": "190050ZRX", "count": "1"},
                    {"item": "210240ZRK", "count": "1"},
                    {"item": "210167ZRK", "count": "1"},
                    {"item": "170046ZRK", "count": "1"},
                    {"item": "220051ZRQ", "count": "1"},
                    {"item": "210062ZRX", "count": "1"},
                    {"item": "200030ZRK", "count": "1"},
                    {"item": "210349ZRK", "count": "1"},
                    {"item": "170141ZRX", "count": "1"},
                    {"item": "210201ZRQ", "count": "1"},
                    {"item": "190151ZRQ", "count": "1"},
                    {"item": "180529ZRQ", "count": "1"},
                    {"item": "170276ZRM", "count": "1"},
                ],
                "smallest": "150277ZRK",
                "count": "197",
                "cardinality": "192",
            },
            "format": {},
        },
        {
            "id": 583119027,
            "name": "ZR_Map",
            "dataTypeName": "text",
            "description": "The map number referenced in Appendix F of the Zoning Resolution for the mapped Mandatory Inclusionary Housing (MIH) area.",
            "fieldName": "zr_map",
            "position": 7,
            "renderTypeName": "text",
            "tableColumnId": 149304428,
            "cachedContents": {
                "non_null": "197",
                "largest": "CD9-Map8 (Area 8)",
                "null": "0",
                "top": [
                    {"item": "CD11-Map 1 (Area 1)", "count": "4"},
                    {"item": "CD12-Map 1 (Area 1)", "count": "4"},
                    {"item": "CD4-Map 1 (Area 1)", "count": "3"},
                    {"item": "CD10-Map 1 (Area 1)", "count": "3"},
                    {"item": "CD1-Map 2 (Area 3)", "count": "3"},
                    {"item": "CD8-Map 1 (Area 1)", "count": "2"},
                    {"item": "CD1-Map 1 (Area 11)", "count": "2"},
                    {"item": "CD1-Map 1 (Area 5)", "count": "2"},
                    {"item": "CD11-Map 2 (Area 2)", "count": "2"},
                    {"item": "CD9-Map 2 (Area 2)", "count": "2"},
                    {"item": "CD11-Map 3 (Area 3)", "count": "2"},
                    {"item": "CD2-Map 2 (Area 1)", "count": "2"},
                    {"item": "CD4-Map 2 (Area 2)", "count": "2"},
                    {"item": "CD4-Map 1 (Area 2)", "count": "2"},
                    {"item": "CD1-Map 2 (Area 2)", "count": "2"},
                    {"item": "CD2-Map 2 (Area 2)", "count": "2"},
                    {"item": "CD6-Map 2 (Area 1)", "count": "2"},
                    {"item": "CD1-Map 2 (Area 4)", "count": "2"},
                    {"item": "CD12-Map 2 (Area 2)", "count": "2"},
                    {"item": "CD9-Map 1 (Area 1)", "count": "2"},
                ],
                "smallest": "c",
                "count": "197",
                "cardinality": "170",
            },
            "format": {},
        },
        {
            "id": 583119028,
            "name": "CD",
            "dataTypeName": "text",
            "description": "Community District where the Mandatory Inclusionary Housing (MIH) area is mapped.",
            "fieldName": "cd",
            "position": 8,
            "renderTypeName": "text",
            "tableColumnId": 149304429,
            "cachedContents": {
                "non_null": "197",
                "largest": "CD14",
                "null": "0",
                "top": [
                    {"item": "1", "count": "41"},
                    {"item": "2", "count": "22"},
                    {"item": "11", "count": "15"},
                    {"item": "6", "count": "15"},
                    {"item": "3", "count": "13"},
                    {"item": "12", "count": "12"},
                    {"item": "8", "count": "11"},
                    {"item": "4", "count": "10"},
                    {"item": "9", "count": "10"},
                    {"item": "16", "count": "9"},
                    {"item": "14", "count": "9"},
                    {"item": "7", "count": "7"},
                    {"item": "5", "count": "7"},
                    {"item": "15", "count": "5"},
                    {"item": "10", "count": "4"},
                    {"item": "9,10,11", "count": "2"},
                    {"item": "4,5", "count": "1"},
                    {"item": "13", "count": "1"},
                    {"item": "2,6", "count": "1"},
                    {"item": "5,7", "count": "1"},
                ],
                "smallest": "1",
                "count": "197",
                "cardinality": "21",
            },
            "format": {},
        },
        {
            "id": 583119029,
            "name": "MIH_Option",
            "dataTypeName": "text",
            "description": "Level of affordability and options applied to the mapped Mandatory Inclusionary Housing (MIH) area.",
            "fieldName": "mih_option",
            "position": 9,
            "renderTypeName": "text",
            "tableColumnId": 149304430,
            "cachedContents": {
                "non_null": "197",
                "largest": "Option 2 and Workforce Option",
                "null": "0",
                "top": [
                    {"item": "Option 1", "count": "78"},
                    {"item": "Option 1 and Option 2", "count": "59"},
                    {"item": "Option 1 and Deep Affordability Option", "count": "37"},
                    {"item": "Option 2", "count": "13"},
                    {"item": "Option 1, Option 2 and Workforce Option", "count": "3"},
                    {"item": "Option 1 and Deep Affordablility Option", "count": "2"},
                    {
                        "item": "Option 1, Option 2 and Deep Affordability Option",
                        "count": "2",
                    },
                    {"item": "Option 1 and Workforce Option", "count": "1"},
                    {"item": "Option 2 and Workforce Option", "count": "1"},
                    {"item": "Option1 and Option 2", "count": "1"},
                ],
                "smallest": "Option 1",
                "count": "197",
                "cardinality": "10",
            },
            "format": {},
        },
        {
            "id": 583119030,
            "name": "Zoning_Map",
            "dataTypeName": "text",
            "description": "Zoning Map index number where the Mandatory Inclusionary Housing (MIH) area is mapped.",
            "fieldName": "zoning_map",
            "position": 10,
            "renderTypeName": "text",
            "tableColumnId": 149304431,
            "cachedContents": {
                "non_null": "197",
                "largest": "9d",
                "null": "0",
                "top": [
                    {"item": "16c", "count": "17"},
                    {"item": "6a", "count": "10"},
                    {"item": "9a", "count": "10"},
                    {"item": "12d", "count": "8"},
                    {"item": "3d", "count": "7"},
                    {"item": "6c", "count": "7"},
                    {"item": "16d", "count": "7"},
                    {"item": "6b", "count": "7"},
                    {"item": "17a", "count": "6"},
                    {"item": "17d", "count": "6"},
                    {"item": "9d", "count": "6"},
                    {"item": "9b", "count": "5"},
                    {"item": "14a", "count": "4"},
                    {"item": "4b", "count": "4"},
                    {"item": "13b", "count": "4"},
                    {"item": "22d", "count": "4"},
                    {"item": "7a", "count": "3"},
                    {"item": "12c", "count": "3"},
                    {"item": "17c", "count": "3"},
                    {"item": "22c", "count": "3"},
                ],
                "smallest": "10a",
                "count": "197",
                "cardinality": "78",
            },
            "format": {},
        },
        {
            "id": 583119031,
            "name": "Project_ID",
            "dataTypeName": "text",
            "description": "Zoning Application Portal (ZAP) project id. ZAP is a DCP project tracking database.",
            "fieldName": "project_id",
            "position": 11,
            "renderTypeName": "text",
            "tableColumnId": 149304432,
            "cachedContents": {
                "non_null": "197",
                "largest": "P2019K0320",
                "null": "0",
                "top": [
                    {"item": "P2013X0135", "count": "3"},
                    {"item": "P2016R0149", "count": "2"},
                    {"item": "P2015K0246", "count": "2"},
                    {"item": "P2016X0350", "count": "2"},
                    {"item": "P2018Q0040", "count": "2"},
                    {"item": "P2014K0469", "count": "2"},
                    {"item": "P2016Q0238", "count": "1"},
                    {"item": "P2016M0355", "count": "1"},
                    {"item": "P2015K0203", "count": "1"},
                    {"item": "2019M0430", "count": "1"},
                    {"item": "P2014K0195", "count": "1"},
                    {"item": "P2012Q0022", "count": "1"},
                    {"item": "P2016M0133", "count": "1"},
                    {"item": "P2013K0511", "count": "1"},
                    {"item": "2020X0451", "count": "1"},
                    {"item": "2020K0259", "count": "1"},
                    {"item": "2020K0270", "count": "1"},
                    {"item": "2019X0252", "count": "1"},
                    {"item": "P2014K0042", "count": "1"},
                    {"item": "P2016M0429", "count": "1"},
                ],
                "smallest": "2018K0356",
                "count": "197",
                "cardinality": "190",
            },
            "format": {},
        },
        {
            "id": 583119032,
            "name": "Shape_Length",
            "dataTypeName": "number",
            "description": "Length of feature in feet.",
            "fieldName": "shape_leng",
            "position": 12,
            "renderTypeName": "number",
            "tableColumnId": 149304433,
            "cachedContents": {
                "non_null": "197",
                "largest": "64147.7682631",
                "null": "0",
                "top": [
                    {"item": "837.017259715", "count": "1"},
                    {"item": "1475.01397751", "count": "1"},
                    {"item": "1668.46469537", "count": "1"},
                    {"item": "1612.77447707", "count": "1"},
                    {"item": "1154.90878323", "count": "1"},
                    {"item": "3585.61865996", "count": "1"},
                    {"item": "1001.77595355", "count": "1"},
                    {"item": "1671.94773123", "count": "1"},
                    {"item": "996.308214763", "count": "1"},
                    {"item": "1790.17662832", "count": "1"},
                    {"item": "19678.3756074", "count": "1"},
                    {"item": "2903.69968725", "count": "1"},
                    {"item": "1380.38618906", "count": "1"},
                    {"item": "898.526930875", "count": "1"},
                    {"item": "1733.50499546", "count": "1"},
                    {"item": "15388.090931", "count": "1"},
                    {"item": "931.180253693", "count": "1"},
                    {"item": "873.389151669", "count": "1"},
                    {"item": "920.60676117", "count": "1"},
                    {"item": "4025.93678561", "count": "1"},
                ],
                "smallest": "470.154914023",
                "count": "197",
                "cardinality": "197",
            },
            "format": {},
        },
        {
            "id": 583119033,
            "name": "Shape_Area",
            "dataTypeName": "number",
            "description": "Area of feature in internal squared feet.",
            "fieldName": "shape_area",
            "position": 13,
            "renderTypeName": "number",
            "tableColumnId": 149304434,
            "cachedContents": {
                "non_null": "197",
                "largest": "9923184.64174",
                "null": "0",
                "top": [
                    {"item": "700002.648777", "count": "1"},
                    {"item": "38506.3754233", "count": "1"},
                    {"item": "186929.474573", "count": "1"},
                    {"item": "96628.5767873", "count": "1"},
                    {"item": "75970.8229562", "count": "1"},
                    {"item": "84501.1399468", "count": "1"},
                    {"item": "62034.6036535", "count": "1"},
                    {"item": "53158.6522722", "count": "1"},
                    {"item": "54569.8692783", "count": "1"},
                    {"item": "6623242.23415", "count": "1"},
                    {"item": "42145.0977177", "count": "1"},
                    {"item": "76548.5129061", "count": "1"},
                    {"item": "44388.9117337", "count": "1"},
                    {"item": "101475.428227", "count": "1"},
                    {"item": "196211.375406", "count": "1"},
                    {"item": "53859.2621075", "count": "1"},
                    {"item": "39028.9523034", "count": "1"},
                    {"item": "309328.446788", "count": "1"},
                    {"item": "276552.311573", "count": "1"},
                    {"item": "36992.1975669", "count": "1"},
                ],
                "smallest": "13548.2572222",
                "count": "197",
                "cardinality": "197",
            },
            "format": {},
        },
    ],
    "license": {
        "name": "Open Data Commons Attribution License",
        "termsLink": "http://opendatacommons.org/licenses/by/1.0/",
    },
    "metadata": {
        "attachments": [
            {
                "filename": MIH_ATTACHMENT_NAME,
                "assetId": "64707c9a-1681-45c2-9d42-cd55bb4fe375",
                "name": "nycmih_metadata.pdf",
            }
        ],
        "custom_fields": {
            "Update": {
                "Automation": "Yes",
                "Update Frequency Details": "never",
                "Date Made Public": "never",
                "Update Frequency": "As needed",
                "Data Change Frequency": "always",
            }
        },
        "rowLabel": "A Mandatorily Included House",
        "availableDisplayTypes": ["table", "fatrow", "page"],
    },
    "owner": {
        "id": "iqqb-gm94",
        "displayName": "DCP Open Data",
        "profileImageUrlLarge": "/api/users/iqqb-gm94/profile_images/LARGE",
        "profileImageUrlMedium": "/api/users/iqqb-gm94/profile_images/THUMB",
        "profileImageUrlSmall": "/api/users/iqqb-gm94/profile_images/TINY",
        "screenName": "DCP Open Data",
        "type": "interactive",
        "userSegment": "site_member",
        "flags": ["acceptedEula", "mayBeStoriesCoOwner", "siteMember"],
    },
    "permissions": {
        "scope": "private",
        "accessLevels": [
            {"name": "viewer", "version": "all"},
            {"name": "contributor", "version": "all"},
            {"name": "owner", "version": "all"},
        ],
        "users": [
            {
                "id": "iqqb-gm94",
                "displayName": "DCP Open Data",
                "email": "dcpopendata@planning.nyc.gov",
                "type": "interactive",
                "accessLevels": [{"name": "current_owner", "version": "all"}],
            }
        ],
    },
    "privateMetadata": {
        "contactEmail": "a@a.com",
        "custom_fields": {
            "Legislative Compliance": {
                "Removed Records?": "Yes",
                "External Frequency (LL 110/2015)": "Historical",
                "Contains Address?": "Yes",
                "Externally Updated- When?": "now",
                "Can Dataset Feasibly Be Automated?": "Yes",
                "DoITT Geocoded- Fields?": "All of 'em",
                "Dataset from the Open Data Plan?": "No",
                "Most Recent Scheduled Publication Date": "whenver a while ago",
                "Address Layout?": "Parsed",
                "Follows Template?": "Yes",
                "Exists Externally? (LL 110/2015)": "Yes",
                "DoITT Geocoded- How?": "Manually",
                "Geocoded?": "Yes",
                "Has Data Dictionary?": "Yes",
                "Original Scheduled Publication Date": "whenver",
            }
        },
    },
    "query": {},
    "rights": [
        "grant",
        "add_column",
        "remove_column",
        "write",
        "add",
        "delete",
        "read",
        "update_column",
        "delete_view",
        "update_view",
        "transfer_ownership",
        "manage_provenance",
    ],
    "tableAuthor": {
        "id": "iqqb-gm94",
        "displayName": "DCP Open Data",
        "profileImageUrlLarge": "/api/users/iqqb-gm94/profile_images/LARGE",
        "profileImageUrlMedium": "/api/users/iqqb-gm94/profile_images/THUMB",
        "profileImageUrlSmall": "/api/users/iqqb-gm94/profile_images/TINY",
        "screenName": "DCP Open Data",
        "type": "interactive",
        "userSegment": "site_member",
        "flags": ["acceptedEula", "mayBeStoriesCoOwner", "siteMember"],
    },
    "tags": ["housing", "house", "building", "development"],
    "flags": ["default", "ownerMayBeContacted", "restorable", "restorePossibleForType"],
}
