{{ config(
    materialized='table',
    indexes=[{'columns': ['geom'], 'type': 'gist'}]
) }}

SELECT
    -- Street name (not in int__lion — follow-up work)
    NULL::text AS "Street",
    NULL::text AS "SAFStreetName",
    feature_type_code AS "FeatureTyp",
    segment_type AS "SegmentTyp",
    incex_flag AS "IncExFlag",
    NULL::text AS "RB_Layer",
    nonped AS "NonPed",
    traffic_direction AS "TrafDir",
    NULL::text AS "TrafSrc",
    special_address_flag AS "SpecAddr",
    face_code AS "FaceCode",
    segment_seqnum AS "SeqNum",
    five_digit_street_code AS "StreetCode",
    NULL::text AS "SAFStreetCode",
    lgc1 AS "LGC1",
    lgc2 AS "LGC2",
    lgc3 AS "LGC3",
    lgc4 AS "LGC4",
    lgc5 AS "LGC5",
    lgc6 AS "LGC6",
    lgc7 AS "LGC7",
    lgc8 AS "LGC8",
    lgc9 AS "LGC9",
    boe_lgc_pointer AS "BOE_LGC",
    lpad(segmentid::text, 7, '0') AS "SegmentID",
    coincident_seg_count::text AS "SegCount",
    segment_locational_status AS "LocStatus",
    l_zip AS "LZip",
    r_zip AS "RZip",
    boroughcode::int AS "LBoro",
    NULL::int AS "RBoro",
    NULL::text AS "L_CD",
    NULL::text AS "R_CD",
    left_dynamic_block AS "LATOMICPOLYGON",
    right_dynamic_block AS "RATOMICPOLYGON",
    left_2020_census_tract_basic::text AS "LCT2020",
    left_2020_census_tract_suffix::text AS "LCT2020Suf",
    right_2020_census_tract_basic::text AS "RCT2020",
    right_2020_census_tract_suffix::text AS "RCT2020Suf",
    left_2020_census_block_basic::text AS "LCB2020",
    left_2020_census_block_suffix AS "LCB2020Suf",
    right_2020_census_block_basic::text AS "RCB2020",
    right_2020_census_block_suffix AS "RCB2020Suf",
    left_2010_census_tract_basic::text AS "LCT2010",
    left_2010_census_tract_suffix::text AS "LCT2010Suf",
    right_2010_census_tract_basic::text AS "RCT2010",
    right_2010_census_tract_suffix::text AS "RCT2010Suf",
    left_2010_census_block_basic::text AS "LCB2010",
    left_2010_census_block_suffix AS "LCB2010Suf",
    right_2010_census_block_basic::text AS "RCB2010",
    right_2010_census_block_suffix AS "RCB2010Suf",
    left_2000_census_tract_basic::text AS "LCT2000",
    left_2000_census_tract_suffix::text AS "LCT2000Suf",
    right_2000_census_tract_basic::text AS "RCT2000",
    right_2000_census_tract_suffix::text AS "RCT2000Suf",
    left_2000_census_block_basic::text AS "LCB2000",
    left_2000_census_block_suffix::text AS "LCB2000Suf",
    right_2000_census_block_basic::text AS "RCB2000",
    right_2000_census_block_suffix::text AS "RCB2000Suf",
    NULL::text AS "LCT1990",
    NULL::text AS "LCT1990Suf",
    NULL::text AS "RCT1990",
    NULL::text AS "RCT1990Suf",
    left_assembly_district AS "LAssmDist",
    left_election_district AS "LElectDist",
    right_assembly_district AS "RAssmDist",
    right_election_district AS "RElectDist",
    split_election_district_flag AS "SplitElect",
    left_school_district AS "LSchlDist",
    right_school_district AS "RSchlDist",
    NULL::text AS "SplitSchl",
    lsubsect AS "LSubSect",
    rsubsect AS "RSubSect",
    sandist_ind AS "SanDistInd",
    from_sectionalmap AS "MapFrom",
    to_sectionalmap AS "MapTo",
    borough_boundary_indicator AS "BoroBndry",
    NULL::text AS "MH_RI_Flag",
    from_x AS "XFrom",
    from_y AS "YFrom",
    to_x AS "XTo",
    to_y AS "YTo",
    center_of_curvature_x::int AS "ArcCenterX",
    center_of_curvature_y::int AS "ArcCenterY",
    curve_flag AS "CurveFlag",
    NULL::int AS "Radius",
    lpad(from_nodeid::text, 7, '0') AS "NodeIDFrom",
    lpad(to_nodeid::text, 7, '0') AS "NodeIDTo",
    from_level_code AS "NodeLevelF",
    to_level_code AS "NodeLevelT",
    continuous_parity_flag AS "ConParity",
    twisted_parity_flag AS "Twisted",
    rw_type::text AS "RW_TYPE",
    physicalid::int AS "PhysicalID",
    genericid::int AS "GenericID",
    nypdid::text AS "NYPDID",
    fdnyid AS "FDNYID",
    l_blockfaceid::text AS "LBlockFaceID",
    r_blockfaceid::text AS "RBlockFaceID",
    lpad(legacy_segmentid::text, 7, '0') AS "LegacyID",
    status AS "Status",
    streetwidth_min::float AS "StreetWidth_Min",
    streetwidth_max::float AS "StreetWidth_Max",
    streetwidth_irr AS "StreetWidth_Irr",
    coalesce(bike_lane_1, ' ') || coalesce(bike_lane_2, ' ') AS "BikeLane",
    bike_traffic_direction AS "BIKE_TRAFDIR",
    NULL::text AS "ACTIVE_FLAG",
    posted_speed::text AS "POSTED_SPEED",
    snow_priority AS "Snow_Priority",
    number_travel_lanes::text AS "Number_Travel_Lanes",
    number_park_lanes::text AS "Number_Park_Lanes",
    number_total_lanes::text AS "Number_Total_Lanes",
    NULL::text AS "Carto_Display_Level",
    fcc AS "FCC",
    right_of_way_type AS "ROW_Type",
    nullif(l_low_hn, '0') AS "LLo_Hyphen",
    nullif(l_high_hn, '0') AS "LHi_Hyphen",
    nullif(r_low_hn, '0') AS "RLo_Hyphen",
    nullif(r_high_hn, '0') AS "RHi_Hyphen",
    NULL::int AS "FromLeft",
    NULL::int AS "ToLeft",
    NULL::int AS "FromRight",
    NULL::int AS "ToRight",
    -- Join_ID links each segment to its AltNames entries (ETL spec §2.7.3).
    -- Non-SAF form; SAF replicants use a different encoding (not produced here).
    {{ lion_join_id() }} AS "Join_ID",
    left_nypd_service_area AS "L_PD_Service_Area",
    right_nypd_service_area AS "R_PD_Service_Area",
    truck_route_type AS "TRUCK_ROUTE_TYPE",
    st_length(geom)::float AS "SHAPE_Length",
    geom
FROM {{ ref('int__lion') }}
WHERE include_in_bytes_lion
