def cscl():
    import streamlit as st

    from . import helpers

    st.title("CSCL QA")
    st.markdown(
        body="""
        Review differences between the development and production CSCL ETL files.
        Select a build version from the sidebar to load the diffs summary.
    """
    )

    builds = helpers.get_builds()
    if builds.index("nightly_qa") is not None:
        # If the "nightly_qa" build is present, select it by default
        default_index = builds.index("nightly_qa")
    else:
        default_index = None
    selected_build = st.sidebar.selectbox(
        "Select a build",
        options=builds,
        index=default_index,
        placeholder="Choose a build version...",
    )

    if not selected_build:
        st.info("Select a build version from the sidebar to get started.")
        return

    with st.spinner(f"Loading data for build {selected_build} ..."):
        prod_version = helpers.get_build_version(selected_build)
        diffs_summary = helpers.get_diffs_summary(selected_build)

    st.info(f"Prod version used to generate diffs: **{prod_version}**")

    st.subheader("Diffs Summary")
    st.markdown(
        body="""
        This table shows which files have differences between the current and previous build.
        
        The **Has diffs** column indicates whether any rows changed. The **# of rows with diffs** column
        shows the count of changed rows.
    """
    )

    st.dataframe(
        diffs_summary,
        width="stretch",
        hide_index=True,
        column_config={
            "Has diffs": st.column_config.CheckboxColumn("Has diffs"),
            "# of rows with diffs": st.column_config.NumberColumn(
                "# of rows with diffs"
            ),
        },
    )

    st.subheader("Diff Row Viewer")
    files_with_diffs = diffs_summary[diffs_summary["Has diffs"]]["File name"].tolist()
    if not files_with_diffs:
        st.info("No files with diffs.")
        return

    selected_file = st.selectbox(
        "Select a file to view diff rows",
        options=files_with_diffs,
    )

    if selected_file:
        with st.spinner(f"Loading diff rows for {selected_file}..."):
            diff_rows = helpers.get_diff_rows(selected_build, selected_file)
        st.caption(
            f"{len(diff_rows)} rows present in dev but not in prod (prod version {prod_version})"
        )
        st.text_area(
            label="Diff rows",
            value="\n".join(diff_rows),
            height=400,
            label_visibility="collapsed",
        )

    st.subheader("Field-Level Diffs (dbt QA Models)")
    st.markdown(
        body="""
        These tables are generated by dbt models in `models/etl_dev_qa/` and provide
        field-level comparisons between dev and prod outputs.
        Not all output files have a corresponding dbt model.
    """
    )
    for group, tables in helpers.DBT_QA_TABLES.items():
        with st.expander(group):
            selected_table = st.selectbox(
                "Select a table",
                options=tables,
                key=f"dbt_table_{group}",
            )
            if selected_table:
                try:
                    with st.spinner(f"Loading {selected_table}..."):
                        df = helpers.get_dbt_qa_table(selected_build, selected_table)
                    st.dataframe(df, use_container_width=True)
                except Exception as e:
                    st.warning(f"Could not load `{selected_table}`: {e}")
