def cscl():
    import streamlit as st

    from . import helpers

    st.title("CSCL QA")
    st.markdown(
        body="""
        Review differences between the development and production CSCL ETL files.
        Select a build version from the sidebar to load the diffs summary.
    """
    )

    builds = helpers.get_builds()
    if builds.index("nightly_qa") is not None:
        # If the "nightly_qa" build is present, select it by default
        default_index = builds.index("nightly_qa")
    else:
        default_index = None
    selected_build = st.sidebar.selectbox(
        "Select a build",
        options=builds,
        index=default_index,
        placeholder="Choose a build version...",
    )

    if not selected_build:
        st.info("Select a build version from the sidebar to get started.")
        return

    with st.spinner(f"Loading data for build {selected_build} ..."):
        prod_version = helpers.get_build_version(selected_build)
        diffs_summary = helpers.get_diffs_summary(selected_build)

    st.info(f"Prod version used to generate diffs: **{prod_version}**")

    dev_build_url = helpers.get_build_output_zip_url(selected_build)
    st.info(f"Dev build files: [Download output.zip]({dev_build_url})")

    st.subheader("Diffs Summary")
    st.markdown(
        body="""
        This table shows which files have differences between the current and previous build.
        
        The **Has diffs** column indicates whether any rows changed. The **# of rows with diffs** column
        shows the count of changed rows.
    """
    )

    st.dataframe(
        diffs_summary,
        width="stretch",
        hide_index=True,
        column_config={
            "Has diffs": st.column_config.CheckboxColumn("Has diffs"),
            "# of rows with diffs": st.column_config.NumberColumn(
                "# of rows with diffs"
            ),
        },
    )

    st.subheader("Field-Level Diffs")
    st.markdown(
        body="""
        These tables provide field-level comparisons between dev and prod outputs
        and are generated by dbt models in `models/etl_dev_qa/`.
        Not all output files are represented in these tables yet.
    """
    )
    for group, tables in helpers.DBT_QA_TABLES.items():
        with st.expander(group):
            selected_table = st.selectbox(
                "Select a table",
                options=tables,
                key=f"dbt_table_{group}",
            )
            if selected_table:
                try:
                    with st.spinner(f"Loading {selected_table}..."):
                        df = helpers.get_dbt_qa_table(selected_build, selected_table)
                    with st.expander("Filter rows", expanded=False):
                        filters = {}
                        for col in df.columns:
                            distinct_values = sorted(
                                df[col].dropna().astype(str).unique().tolist()
                            )
                            if len(distinct_values) <= 1:
                                continue
                            selected_values = st.multiselect(
                                col,
                                options=distinct_values,
                                default=[],
                                key=f"filter_{group}_{selected_table}_{col}",
                            )
                            if selected_values:
                                filters[col] = selected_values
                    filtered_df = df.copy()
                    for col, values in filters.items():
                        filtered_df = filtered_df[
                            filtered_df[col].astype(str).isin(values)
                        ]
                    st.caption(f"{len(filtered_df):,} of {len(df):,} rows")
                    st.dataframe(filtered_df, use_container_width=True)

                    _record_cols = {
                        "comparison_id",
                        "comparison_column",
                        "build_table_name",
                        "production_table_name",
                    }
                    if _record_cols.issubset(df.columns):
                        with st.expander("View source records", expanded=False):
                            _meta = df.iloc[0]
                            _id_col = _meta["comparison_column"]
                            _build_tbl = _meta["build_table_name"]
                            _prod_tbl = _meta["production_table_name"]
                            _ids = sorted(
                                filtered_df["comparison_id"]
                                .dropna()
                                .astype(str)
                                .unique()
                                .tolist()
                            )
                            _selected_id = st.selectbox(
                                "comparison_id",
                                options=[""] + _ids,
                                key=f"record_viewer_{group}_{selected_table}",
                            )
                            if _selected_id:
                                _dev_col, _prod_col = st.columns(2)
                                with _dev_col:
                                    st.caption(f"Dev: `{_build_tbl}`")
                                    try:
                                        _dev_df = helpers.get_record_by_comparison_id(
                                            selected_build,
                                            _build_tbl,
                                            _id_col,
                                            _selected_id,
                                        )
                                        st.dataframe(
                                            _dev_df.T, use_container_width=True
                                        )
                                    except Exception as e:
                                        st.warning(f"Could not load: {e}")
                                with _prod_col:
                                    st.caption(f"Prod: `{_prod_tbl}`")
                                    try:
                                        _prod_df = helpers.get_record_by_comparison_id(
                                            selected_build,
                                            _prod_tbl,
                                            _id_col,
                                            _selected_id,
                                        )
                                        st.dataframe(
                                            _prod_df.T, use_container_width=True
                                        )
                                    except Exception as e:
                                        st.warning(f"Could not load: {e}")
                    else:
                        st.caption(
                            "ℹ️ Source record lookup not available for this table — missing diff metadata columns."
                        )
                except Exception as e:
                    st.warning(
                        f"Could not load `{selected_build}.{selected_table}`: {e}"
                    )

    st.subheader("Browse Build Tables")
    st.markdown(
        body="Explore any table in the build's Postgres schema. Add multiple tables to compare side by side."
    )

    slot_key = f"browse_table_slots_{selected_build}"
    if slot_key not in st.session_state:
        st.session_state[slot_key] = [0]

    available_tables = helpers.get_build_tables(selected_build)

    for slot_idx in st.session_state[slot_key]:
        col_select, col_remove = st.columns([5, 1])
        with col_select:
            chosen = st.selectbox(
                "Select a table",
                options=[""] + available_tables,
                key=f"browse_slot_{selected_build}_{slot_idx}",
                label_visibility="collapsed",
                placeholder="Choose a table...",
            )
        with col_remove:
            if st.button(
                "✕",
                key=f"browse_remove_{selected_build}_{slot_idx}",
                help="Remove this table",
            ):
                st.session_state[slot_key] = [
                    s for s in st.session_state[slot_key] if s != slot_idx
                ]
                st.rerun()

        if chosen:
            try:
                with st.spinner(f"Loading {chosen}..."):
                    df = helpers.get_build_table(selected_build, chosen)
                st.caption(f"{len(df):,} rows · {len(df.columns)} columns")
                st.dataframe(df, use_container_width=True)
            except Exception as e:
                st.warning(f"Could not load `{chosen}`: {e}")

    if st.button("＋ Add table", key=f"browse_add_{selected_build}"):
        next_idx = (
            max(st.session_state[slot_key]) + 1 if st.session_state[slot_key] else 0
        )
        st.session_state[slot_key] = st.session_state[slot_key] + [next_idx]
        st.rerun()

    st.subheader("Diff Row Viewer")
    files_with_diffs = diffs_summary[diffs_summary["Has diffs"]]["File name"].tolist()
    if not files_with_diffs:
        st.info("No files with diffs.")
        return

    selected_file = st.selectbox(
        "Select a file to view diff rows",
        options=files_with_diffs,
    )

    if selected_file:
        with st.spinner(f"Loading diff rows for {selected_file}..."):
            diff_rows = helpers.get_diff_rows(selected_build, selected_file)
        st.caption(
            f"{len(diff_rows)} rows present in dev but not in prod (prod version {prod_version})"
        )
        st.text_area(
            label="Diff rows",
            value="\n".join(diff_rows),
            height=400,
            label_visibility="collapsed",
        )
