name: Community Board Budget Requests
product: db-cbbr
version: FY2027
inputs:
  missing_versions_strategy: find_latest
  datasets:
  # primary data
  - name: dcp_cbbr_requests
  - name: omb_cbbr_agency_responses
  # spatial data
  - name: dcp_cbbr_manualmappings
  - name: dpr_parksproperties
  - name: dcp_facilities
  - name: doitt_buildingfootprints
  # other data
  - name: dcp_managing_agencies_lookup
