WITH lift_raw AS (
    SELECT * FROM {{ source('recipe_sources', 'lift_csv') }}
),

-- Every column below is explicitly aliased, even where the alias is just the
-- lowercased source name (e.g. `BORO AS boro`) - DuckDB is case-insensitive when
-- *referencing* a column but preserves the source's original casing for the
-- *stored* output name unless given an explicit alias. Without these aliases the
-- output columns silently revert to lift_csv's raw mixed-case CSV headers (e.g.
-- `BORO`, `PARCEL_ADDRESS`) instead of snake_case. A prior formatting pass
-- stripped these aliases as "redundant self-aliases" (`BORO AS boro` -> `boro`)
-- since it doesn't know DuckDB treats identical-modulo-case aliases as
-- meaningful here - don't let a formatter do that again.
final AS (
    SELECT
    BORO AS boro,
    BLOCK AS block,
    LOT AS lot,
    BBL AS bbl,
    PLUTO_BBL AS pluto_bbl,
    HOLDS_BBL AS holds_bbl,
    LEASE_OUT_BBL AS lease_out_bbl,
    USE_BBL AS use_bbl,
    ULURP_BBL AS ulurp_bbl,
    PARCEL_ADDRESS AS parcel_address,
    LOCATION AS location,
    PARCEL_NAME AS parcel_name,
    JURIS AS juris,
    MGMT AS mgmt,
    RENEWAL_AREA_NAME AS renewal_area_name,
    MOA_METHOD AS moa_method,
    MOA_DATE AS moa_date,
    LUR_URBANRENEWALSITE AS lur_urbanrenewalsite,
    LUR_WATERFRONT AS lur_waterfront,
    LUR_UNDERWATER AS lur_underwater,
    LUR_BEDOFSTREET AS lur_bedofstreet,
    TITLE_CHECK AS title_check,
    LUR_CEMETERY AS lur_cemetery,
    NO_STREET_FRONTAGE AS no_street_frontage,
    LUR_SLIVERLOT AS lur_sliverlot,
    LUR_COMMONOPENSPACE AS lur_commonopenspace,
    LUR_ACCESSWAY AS lur_accessway,
    IBZ_NAME AS ibz_name,
    BLD_CLASS_CATEGORY AS bld_class_category,
    BLD_CLASS_DESCRIPTION AS bld_class_description,
    ASSESSED_VALUE AS assessed_value,
    ZZZ_PLUTO_DATA_ZZZ AS zzz_pluto_data_zzz,
    LotFront AS lotfront,
    LotDepth AS lotdepth,
    LotArea AS lotarea,
    BldgArea AS bldgarea,
    NumBldgs AS numbldgs,
    NumFloors AS numfloors,
    AssessLand AS assessland,
    AssessTot AS assesstot,
    CD AS cd,
    Council AS council,
    ZoneDist1 AS zonedist1,
    ZoneDist2 AS zonedist2,
    ZoneDist3 AS zonedist3,
    ZoneDist4 AS zonedist4,
    Overlay1 AS overlay1,
    Overlay2 AS overlay2,
    SPDist1 AS spdist1,
    SPDist2 AS spdist2,
    SPDist3 AS spdist3,
    Landmark AS landmark,
    HistDist AS histdist,
    ResidFAR AS residfar,
    CommFAR AS commfar,
    FacilFAR AS facilfar,
    UnitsRes AS unitsres,
    PFIRM15_FLAG AS pfirm15_flag,
    Latitude AS latitude,
    Longitude AS longitude,
    ZZZ_HOLDS_DATA_ZZZ AS zzz_holds_data_zzz,
    HOLDERS AS holders,
    PROJECT_NAMES AS project_names,
    MILESTONE_DESC AS milestone_desc,
    MILESTONE_DATES AS milestone_dates,
    ZZZ_LEASE_OUT_DATA_ZZZ AS zzz_lease_out_data_zzz,
    TENANTS AS tenants,
    LEASE_TYPES AS lease_types,
    EXPIRATION_DATES AS expiration_dates,
    ZZZ_PRIMARY_USE_DATA_ZZZ AS zzz_primary_use_data_zzz,
    AgencyS AS agencys,
    OwnedLeased AS ownedleased,
    Primary_Uses_Text AS primary_uses_text,
    ZZZ_ULURPS_DATA_ZZZ AS zzz_ulurps_data_zzz,
    Status AS status,
    ULURP_Notes AS ulurp_notes,
    ULURP_Num AS ulurp_num,
    CEQR_Num AS ceqr_num,
    FinalLanguage AS finallanguage,
    BOE_CAL_NO AS boe_cal_no,
    ULURP_Name AS ulurp_name,
    Primary_Applicant AS primary_applicant,
    ZZZ_LIFT_DATA_ZZZ AS zzz_lift_data_zzz,
    UNITPOTENTIAL AS unitpotential,
    LAA AS laa,
    DEV_FLAGS AS dev_flags,
    POA AS poa,
    AHFT AS ahft,
    -- DISPLACEMENT_RISK_FORMULA, CPSPENTTOTAL, CPPROJECTS are empty placeholder
    -- columns in the source spreadsheet - passed through null here, populated in
    -- product/lift_supplemented.sql
    DISPLACEMENT_RISK_FORMULA AS displacement_risk_formula,
    TRANSITGEOG AS transitgeog,
    CPSPENTTOTAL AS cpspenttotal,
    CPPROJECTS AS cpprojects,
    PROPOSAL AS proposal,
    LAST_UPDATED AS last_updated,
    POA_COMMITMENT AS poa_commitment,
    REDEV_SUMMARY AS redev_summary,
    REDEV_STRATEGY AS redev_strategy,
    REDEV_PRIORITY AS redev_priority,
    REDEV_STUDY AS redev_study,
    CP_REMEDIATION AS cp_remediation,
    CAPITALNEEDS_UNFUNDED AS capitalneeds_unfunded,
    SITEPREP_COSTS AS siteprep_costs,
    SITEPREP_DESC AS siteprep_desc,
    RLV_AMOUNT AS rlv_amount,
    RLV_DESC AS rlv_desc
    FROM lift_raw
)

SELECT * FROM final
