WITH lift_raw AS (
    SELECT * FROM {{ source('recipe_sources', 'lift_csv') }}
),

-- Every column below is explicitly aliased, even where the alias is just the
-- lowercased source name (e.g. `BORO AS boro`) - DuckDB is case-insensitive when
-- *referencing* a column but preserves the source's original casing for the
-- *stored* output name unless given an explicit alias. Without these aliases the
-- output columns silently revert to lift_csv's raw mixed-case CSV headers (e.g.
-- `BORO`, `PARCEL_ADDRESS`) instead of snake_case. A prior formatting pass
-- stripped these aliases as "redundant self-aliases" (`BORO AS boro` -> `boro`)
-- since it doesn't know DuckDB treats identical-modulo-case aliases as
-- meaningful here - don't let a formatter do that again.
-- Text columns are trimmed: DCAS's extract carries stray leading/trailing spaces
-- (e.g. ' STUYVESANT HIGH SCHOOL').
final AS (
    SELECT
    BORO AS boro,
    BLOCK AS block,
    LOT AS lot,
    BBL AS bbl,
    PLUTO_BBL AS pluto_bbl,
    HOLDS_BBL AS holds_bbl,
    LEASE_OUT_BBL AS lease_out_bbl,
    USE_BBL AS use_bbl,
    ULURP_BBL AS ulurp_bbl,
    TRIM(PARCEL_ADDRESS) AS parcel_address,
    TRIM(LOCATION) AS location,
    TRIM(PARCEL_NAME) AS parcel_name,
    TRIM(JURIS) AS juris,
    TRIM(MGMT) AS mgmt,
    TRIM(RENEWAL_AREA_NAME) AS renewal_area_name,
    TRIM(MOA_METHOD) AS moa_method,
    TRIM(MOA_DATE) AS moa_date,
    TRIM(LUR_URBANRENEWALSITE) AS lur_urbanrenewalsite,
    TRIM(LUR_WATERFRONT) AS lur_waterfront,
    TRIM(LUR_UNDERWATER) AS lur_underwater,
    TRIM(LUR_BEDOFSTREET) AS lur_bedofstreet,
    TRIM(TITLE_CHECK) AS title_check,
    TRIM(LUR_CEMETERY) AS lur_cemetery,
    TRIM(NO_STREET_FRONTAGE) AS no_street_frontage,
    TRIM(LUR_SLIVERLOT) AS lur_sliverlot,
    TRIM(LUR_COMMONOPENSPACE) AS lur_commonopenspace,
    TRIM(LUR_ACCESSWAY) AS lur_accessway,
    TRIM(IBZ_NAME) AS ibz_name,
    TRIM(BLD_CLASS_CATEGORY) AS bld_class_category,
    TRIM(BLD_CLASS_DESCRIPTION) AS bld_class_description,
    ASSESSED_VALUE AS assessed_value,
    TRIM(ZZZ_PLUTO_DATA_ZZZ) AS zzz_pluto_data_zzz,
    LotFront AS lotfront,
    LotDepth AS lotdepth,
    LotArea AS lotarea,
    BldgArea AS bldgarea,
    NumBldgs AS numbldgs,
    NumFloors AS numfloors,
    AssessLand AS assessland,
    AssessTot AS assesstot,
    CD AS cd,
    Council AS council,
    TRIM(ZoneDist1) AS zonedist1,
    TRIM(ZoneDist2) AS zonedist2,
    TRIM(ZoneDist3) AS zonedist3,
    TRIM(ZoneDist4) AS zonedist4,
    TRIM(Overlay1) AS overlay1,
    TRIM(Overlay2) AS overlay2,
    TRIM(SPDist1) AS spdist1,
    TRIM(SPDist2) AS spdist2,
    TRIM(SPDist3) AS spdist3,
    TRIM(Landmark) AS landmark,
    TRIM(HistDist) AS histdist,
    ResidFAR AS residfar,
    CommFAR AS commfar,
    FacilFAR AS facilfar,
    UnitsRes AS unitsres,
    PFIRM15_FLAG AS pfirm15_flag,
    Latitude AS latitude,
    Longitude AS longitude,
    TRIM(ZZZ_HOLDS_DATA_ZZZ) AS zzz_holds_data_zzz,
    TRIM(HOLDERS) AS holders,
    TRIM(PROJECT_NAMES) AS project_names,
    TRIM(MILESTONE_DESC) AS milestone_desc,
    TRIM(MILESTONE_DATES) AS milestone_dates,
    TRIM(ZZZ_LEASE_OUT_DATA_ZZZ) AS zzz_lease_out_data_zzz,
    TRIM(TENANTS) AS tenants,
    TRIM(LEASE_TYPES) AS lease_types,
    TRIM(EXPIRATION_DATES) AS expiration_dates,
    TRIM(ZZZ_PRIMARY_USE_DATA_ZZZ) AS zzz_primary_use_data_zzz,
    TRIM(AgencyS) AS agencys,
    TRIM(OwnedLeased) AS ownedleased,
    TRIM(Primary_Uses_Text) AS primary_uses_text,
    TRIM(ZZZ_ULURPS_DATA_ZZZ) AS zzz_ulurps_data_zzz,
    TRIM(Status) AS status,
    TRIM(ULURP_Notes) AS ulurp_notes,
    TRIM(ULURP_Num) AS ulurp_num,
    TRIM(CEQR_Num) AS ceqr_num,
    TRIM(FinalLanguage) AS finallanguage,
    TRIM(BOE_CAL_NO) AS boe_cal_no,
    TRIM(ULURP_Name) AS ulurp_name,
    TRIM(Primary_Applicant) AS primary_applicant,
    TRIM(ZZZ_LIFT_DATA_ZZZ) AS zzz_lift_data_zzz,
    TRIM(UNITPOTENTIAL) AS unitpotential,
    TRIM(LAA) AS laa,
    TRIM(DEV_FLAGS) AS dev_flags,
    TRIM(POA) AS poa,
    TRIM(AHFT) AS ahft,
    -- DISPLACEMENT_RISK_FORMULA, CPSPENTTOTAL, CPPROJECTS are empty placeholder
    -- columns in the source spreadsheet - passed through null here, populated in
    -- product/lift_supplemented.sql
    TRIM(DISPLACEMENT_RISK_FORMULA) AS displacement_risk_formula,
    TRIM(TRANSITGEOG) AS transitgeog,
    TRIM(CPSPENTTOTAL) AS cpspenttotal,
    TRIM(CPPROJECTS) AS cpprojects,
    TRIM(PROPOSAL) AS proposal,
    TRIM(LAST_UPDATED) AS last_updated,
    TRIM(POA_COMMITMENT) AS poa_commitment,
    TRIM(REDEV_SUMMARY) AS redev_summary,
    TRIM(REDEV_STRATEGY) AS redev_strategy,
    TRIM(REDEV_PRIORITY) AS redev_priority,
    TRIM(REDEV_STUDY) AS redev_study,
    TRIM(CP_REMEDIATION) AS cp_remediation,
    TRIM(CAPITALNEEDS_UNFUNDED) AS capitalneeds_unfunded,
    TRIM(SITEPREP_COSTS) AS siteprep_costs,
    TRIM(SITEPREP_DESC) AS siteprep_desc,
    TRIM(RLV_AMOUNT) AS rlv_amount,
    TRIM(RLV_DESC) AS rlv_desc
    FROM lift_raw
)

SELECT * FROM final
