SELECT
    'altsegmentdata' AS source_table,
    segmentid,
    lionkey,
    RIGHT(b5sc, 5) AS five_digit_street_code,
    b5sc || lgc1 AS b7sc,
    saftype,
    l_low_hn,
    l_high_hn,
    r_low_hn,
    r_high_hn,
    low_hn_suffix,
    high_hn_suffix,
    lgc1,
    lgc2,
    lgc3,
    lgc4,
    borough,
    zipcode,
    created_by,
    created_date,
    modified_by,
    modified_date,
    LPAD(alt_segment_seqnum::INT::TEXT, 5, '0') AS alt_segment_seqnum,
    boe_preferred_lgc_flag AS boe_lgc_pointer,
    b5sc,
    sosindicator,
    feature_type AS feature_type_code,
    from_to_indicator,
    from_to_indicator = 'R' AS reversed,
    alt_segdata_type,
    seglocstatus,
    lgc5,
    lgc6,
    lgc7,
    lgc8,
    lgc9,
    twisted_parity_flag,
    globalid,
    lsubsect,
    rsubsect,
    sandist_ind,
    ogc_fid,
    data_library_version
FROM {{ source("recipe_sources", "dcp_cscl_altsegmentdata") }}
WHERE
    alt_segdata_type != 'S' -- S denotes an SAF record
    AND segmentid IS NOT NULL
