-- Ignore "Line is too long" sqlfluff rule
-- noqa: disable=LT05

SELECT
    project_id AS "Project ID",
    "Project_Status_Start_Date" AS "Project Status Start Date",
    "Project_Status_End_Date" AS "Project Status End Date",
    entirely_within_quarter_mile_of_eligible_tract AS "Entirely Within Quarter Mile of Eligible Tract",
    entirely_within_half_mile_of_eligible_tract AS "Entirely Within Half Mile of Eligible Tract",
    partially_within_quarter_mile_of_eligible_tract AS "Partially Within Quarter Mile of Eligible Tract",
    partially_within_half_mile_of_eligible_tract AS "Partially Within Half Mile Of Eligible Tract",
    distinct_bbls AS "Distinct BBLs",
    bbls AS "ALL ZAP BBLs",
    "Project_Name" AS "Project Name",
    "Applicant_Type" AS "Applicant Type",
    "CEQR_Complexity" AS "CEQR Complexity",
    "ULURP_/_Non_ULURP" AS "ULURP / Non ULURP",
    "System_Lead_Action" AS "System Lead Action",
    "ZR_Section_Number" AS "ZR Section Number",
    "Certified/Referred",
    "Validated_City_Council_Districts" AS "Validated City Council Districts",
    "CEQR_Type" AS "CEQR Type",
    "Lead_Agency" AS "Lead Agency",
    "Lead_Division" AS "Lead Division",
    "Lead_Planner" AS "Lead Planner",
    "Major_Initiative" AS "Major Initiative",
    "Current_Milestone" AS "Current Milestone",
    "Current_Milestone_Actual_Start_Date_(Used_for_PCF)" AS "Actual Start Date (Current Milestone) (Project Milestone)",
    "Project_Status" AS "Project Status",
    "Project_Brief" AS "Project Brief",
    "EAS_/_EIS" AS "EAS / EIS",
    "Pre_Cert_Start_Date" AS "Pre Cert Start Date",
    "Borough",
    "Last_Milestone" AS "Last Milestone",
    "Last_Milestone_Date" AS "Last Milestone Date",
    "Validated_Community_Districts" AS "Validated Community Districts"
FROM {{ ref("cdbg_zap_eligibility") }}
