FROM prefecthq/prefect:2-python3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

# COPY dcpy ./dcpy
# RUN pip install -e .

COPY . .

CMD ["prefect", "worker", "start", "--pool", "default-work-pool", "--type", "process"]