-- EXPORT DevDB
DROP TABLE IF EXISTS EXPORT_DEVDB CASCADE;
SELECT *
INTO EXPORT_DEVDB
FROM FINAL_DEVDB
WHERE (
    DATE_COMPLETE::date <=: 'CAPTURE_DATE'
    OR (
        DATE_COMPLETE IS NULL
        AND DATE_PERMITTD::date <=: 'CAPTURE_DATE'
    )
    OR (
        DATE_COMPLETE IS NULL
        AND DATE_PERMITTD IS NULL
        AND DATE_FILED::date <=: 'CAPTURE_DATE'
    )
);

-- EXPORT HousingDB
CREATE VIEW EXPORT_HOUSING AS
SELECT *
FROM EXPORT_DEVDB
WHERE RESID_FLAG = 'Residential';

-- Switch to 10 char fieldnames
CREATE VIEW SHP_DEVDB AS
SELECT
    JOB_NUMBER AS "Job_Number",
    JOB_TYPE AS "Job_Type",
    RESID_FLAG AS "ResidFlag",
    NONRES_FLAG AS "NonresFlag",
    JOB_INACTIVE AS "Job_Inactv",
    JOB_STATUS AS "Job_Status",
    COMPLETE_YEAR AS "CompltYear",
    COMPLETE_QRTR AS "CompltQrtr",
    PERMIT_YEAR AS "PermitYear",
    PERMIT_QRTR AS "PermitQrtr",
    CLASSA_INIT AS "ClassAInit",
    CLASSA_PROP AS "ClassAProp",
    CLASSA_NET AS "ClassANet",
    CLASSA_HNYAFF::numeric AS "ClassA_HNY",
    HOTEL_INIT AS "HotelInit",
    HOTEL_PROP AS "HotelProp",
    OTHERB_INIT AS "OtherBInit",
    OTHERB_PROP AS "OtherBProp",
    UNITS_CO AS "Units_CO",
    BORO AS "Boro",
    BIN AS "BIN",
    BBL AS "BBL",
    ADDRESS_NUMBR AS "AddressNum",
    ADDRESS_ST AS "AddressSt",
    ADDRESS AS "Address",
    OCC_INITIAL AS "Occ_Init",
    OCC_PROPOSED AS "Occ_Prop",
    BLDG_CLASS AS "Bldg_Class",
    JOB_DESC AS "Job_Desc",
    DESC_OTHER AS "Desc_Other",
    DATE_FILED AS "DateFiled",
    DATE_STATUSD AS "DateStatsD",
    DATE_STATUSP AS "DateStatsP",
    DATE_PERMITTD AS "DatePermit",
    DATE_STATUSR AS "DateStatsR",
    DATE_STATUSX AS "DateStatsX",
    DATE_LASTUPDT AS "DateLstUpd",
    DATE_COMPLETE AS "DateComplt",
    ZONINGDIST1 AS "ZoningDst1",
    ZONINGDIST2 AS "ZoningDst2",
    ZONINGDIST3 AS "ZoningDst3",
    SPECIALDIST1 AS "SpeclDst1",
    SPECIALDIST2 AS "SpeclDst2",
    LANDMARK AS "Landmark",
    ZSF_INIT AS "ZSF_Init",
    ZSF_PROP AS "ZSF_Prop",
    ZUG_INIT AS "ZUG_Init",
    ZUG_PROP AS "ZUG_Prop",
    ZSFR_PROP AS "ZSFR_Prop",
    ZSFC_PROP AS "ZSFC_Prop",
    ZSFCF_PROP AS "ZSFCF_Prop",
    ZSFM_PROP AS "ZSFM_Prop",
    PRKNGPROP AS "PrkngProp",
    STORIES_INIT AS "FloorsInit",
    STORIES_PROP AS "FloorsProp",
    HEIGHT_INIT AS "HeightInit",
    HEIGHT_PROP AS "HeightProp",
    CONSTRUCTNSF AS "CnstrctnSF",
    ENLARGEMENT AS "Enlargemnt",
    ENLARGEMENTSF AS "EnlrgSF",
    COSTESTIMATE AS "CostEst",
    LOFTBOARDCERT AS "LoftBoard",
    EDESIGNATION AS "eDesigntn",
    CURBCUT AS "CurbCut",
    TRACTHOMES AS "TractHomes",
    OWNERSHIP AS "Ownership",
    OWNER_NAME AS "OwnrName",
    OWNER_ADDRESS AS "OwnrAddr",
    OWNER_ZIPCODE AS "OwnrZip",
    OWNER_PHONE AS "OwnrPhone",
    PLUTO_UNITRES AS "PL_UnitRes",
    PLUTO_BLDGSF AS "PL_BldgSF",
    PLUTO_COMSF AS "PL_ComSF",
    PLUTO_OFFCSF AS "PL_OffcSF",
    PLUTO_RETLSF AS "PL_RetlSF",
    PLUTO_RESSF AS "PL_ResSF",
    PLUTO_YRBUILT AS "PL_YrBuilt",
    PLUTO_YRALT1 AS "PL_YrAlt1",
    PLUTO_YRALT2 AS "PL_YrAlt2",
    PLUTO_HISTDST AS "PL_Histdst",
    PLUTO_LANDMK AS "PL_Landmk",
    PLUTO_BLDGCLS AS "PL_BldgCls",
    PLUTO_LANDUSE AS "PL_LandUse",
    PLUTO_OWNER AS "PL_Owner",
    PLUTO_OWNTYPE AS "PL_OwnType",
    PLUTO_CONDO AS "PL_Condo",
    PLUTO_BLDGS AS "PL_Bldgs",
    PLUTO_FLOORS AS "PL_Floors",
    PLUTO_VERSION AS "PL_Version",
    CENBLOCK2020 AS "CenBlock20",
    CENTRACT2020 AS "CenTract20",
    BCTCB2020 AS "BCTCB2020",
    BCT2020 AS "BCT2020",
    NTA2020 AS "NTA2020",
    NTANAME2020 AS "NTAName20",
    CDTA2020 AS "CDTA2020",
    CDTANAME2020 AS "CDTAName20",
    COMUNITYDIST AS "CommntyDst",
    COUNCILDIST AS "CouncilDst",
    SCHOOLSUBDIST AS "SchSubDist",
    SCHOOLCOMMNTY AS "SchCommnty",
    SCHOOLELMNTRY AS "SchElmntry",
    SCHOOLMIDDLE AS "SchMiddle",
    FIRECOMPANY AS "FireCmpany",
    FIREBATTALION AS "FireBattln",
    FIREDIVISION AS "FireDivsn",
    POLICEPRECNCT AS "PolicePcnt",
    -- DEPDrainArea as "DEPDrainAr",
    -- DEPPumpStatn as "DEPPumpStn",
    PLUTO_FIRM07 AS "PL_FIRM07",
    PLUTO_PFIRM15 AS "PL_PFIRM15",
    LATITUDE AS "Latitude",
    LONGITUDE AS "Longitude",
    DATASOURCE AS "DataSource",
    GEOMSOURCE AS "GeomSource",
    DCPEDITFIELDS AS "DCPEdited",
    HNY_ID AS "HNY_ID",
    HNY_JOBRELATE AS "HNY_Relate",
    VERSION AS "Version",
    ST_SETSRID(ST_MAKEPOINT(LONGITUDE, LATITUDE), 4326) AS GEOM
FROM EXPORT_DEVDB;

CREATE VIEW SHP_HOUSING AS
SELECT *
FROM SHP_DEVDB
WHERE "ResidFlag" = 'Residential';


-- internal project-level files
-- created for distribution on m drive
CREATE VIEW HOUSINGDB_POST2010_ALL_INTERNAL AS
SELECT: internal_columns
FROM SHP_HOUSING
WHERE "CompltYear"::integer >= '2010'::integer OR ("CompltYear" IS NULL AND "DateLstUpd"::date >= '2010-01-01');

CREATE VIEW HOUSINGDB_POST2010_INTERNAL AS
SELECT *
FROM HOUSINGDB_POST2010_ALL_INTERNAL
WHERE "Job_Inactv" IS NULL;

CREATE VIEW HOUSINGDB_POST2010_COMPLETED_JOBS_INTERNAL AS
SELECT *
FROM HOUSINGDB_POST2010_INTERNAL
WHERE "CompltYear"::integer >= '2010'::integer;

CREATE VIEW HOUSINGDB_POST2010_INCOMPLETE_JOBS_INTERNAL AS
SELECT *
FROM HOUSINGDB_POST2010_INTERNAL
WHERE "CompltYear" IS NULL;

CREATE VIEW HOUSINGDB_POST2010_INACTIVE_JOBS_INTERNAL AS
SELECT *
FROM HOUSINGDB_POST2010_ALL_INTERNAL
WHERE "Job_Inactv" IS NOT NULL;

CREATE VIEW HOUSINGDB_POST2010_INACTIVE_INCLUDED_INTERNAL AS
SELECT *
FROM HOUSINGDB_POST2010_ALL_INTERNAL;


-- external project-level files
-- created for distribution via BYTES by GIS team
CREATE VIEW HOUSINGDB_POST2010_ALL_EXTERNAL AS
SELECT: external_columns
FROM HOUSINGDB_POST2010_ALL_INTERNAL;

CREATE VIEW HOUSINGDB_POST2010_EXTERNAL AS
SELECT: external_columns
FROM HOUSINGDB_POST2010_INTERNAL;

CREATE VIEW HOUSINGDB_POST2010_COMPLETED_JOBS_EXTERNAL AS
SELECT: external_columns
FROM HOUSINGDB_POST2010_COMPLETED_JOBS_INTERNAL;

CREATE VIEW HOUSINGDB_POST2010_INCOMPLETE_JOBS_EXTERNAL AS
SELECT: external_columns
FROM HOUSINGDB_POST2010_INCOMPLETE_JOBS_INTERNAL;

CREATE VIEW HOUSINGDB_POST2010_INACTIVE_JOBS_EXTERNAL AS
SELECT: external_columns
FROM HOUSINGDB_POST2010_INACTIVE_JOBS_INTERNAL;

CREATE VIEW HOUSINGDB_POST2010_INACTIVE_INCLUDED_EXTERNAL AS
SELECT: external_columns
FROM HOUSINGDB_POST2010_INACTIVE_INCLUDED_INTERNAL
