/*
IN PREVIOUS VERSION:
    pluto_merge.sql
*/
DROP TABLE IF EXISTS PLUTO_DEVDB CASCADE;
SELECT
    A.*,
    B.VERSION AS PLUTO_VERSION,
    B.BBL AS MPLUTO_BBL,
    B.UNITSRES AS PLUTO_UNITRES,
    B.BLDGAREA AS PLUTO_BLDGSF,
    B.COMAREA AS PLUTO_COMSF,
    B.OFFICEAREA AS PLUTO_OFFCSF,
    B.RETAILAREA AS PLUTO_RETLSF,
    B.RESAREA AS PLUTO_RESSF,
    B.YEARBUILT AS PLUTO_YRBUILT,
    B.YEARALTER1 AS PLUTO_YRALT1,
    B.YEARALTER2 AS PLUTO_YRALT2,
    B.BLDGCLASS AS PLUTO_BLDGCLS,
    B.LANDUSE AS PLUTO_LANDUSE,
    B.OWNERTYPE AS PLUTO_OWNTYPE,
    B.OWNERNAME AS PLUTO_OWNER,
    B.CONDONO AS PLUTO_CONDO,
    B.NUMBLDGS AS PLUTO_BLDGS,
    B.NUMFLOORS AS PLUTO_FLOORS,
    B.FIRM07_FLA AS PLUTO_FIRM07,
    B.PFIRM15_FL AS PLUTO_PFIRM15,
    B.HISTDIST AS PLUTO_HISTDST,
    B.LANDMARK AS PLUTO_LANDMK
INTO PLUTO_DEVDB
FROM INIT_DEVDB AS A
LEFT JOIN DCP_MAPPLUTO AS B
    ON A.GEO_BBL = B.BBL::bigint::text;
CREATE INDEX PLUTO_DEVDB_JOB_NUMBER_IDX ON PLUTO_DEVDB (JOB_NUMBER);
