DROP TABLE IF EXISTS qaqc_historic;
CREATE TABLE qaqc_historic (
    version text,
    b_likely_occ_desc text,
    b_large_alt_reduction text,
    b_nonres_with_units text,
    units_co_prop_mismatch text,
    partially_complete text,
    units_init_null text,
    units_prop_null text,
    units_res_accessory text,
    outlier_demo_20plus text,
    outlier_nb_500plus text,
    outlier_top_alt_increase text,
    dup_bbl_address_units text,
    dup_bbl_address text,
    inactive_with_update text,
    no_work_job text,
    geo_water text,
    geo_taxlot text,
    geo_null_latlong text,
    geo_null_boundary text,
    invalid_date_filed text,
    invalid_date_lastupdt text,
    invalid_date_statusd text,
    invalid_date_statusp text,
    invalid_date_statusr text,
    invalid_date_statusx text,
    incomp_tract_home text,
    dem_nb_overlap text
);
