DROP TABLE IF EXISTS qaqc_historic;
CREATE TABLE qaqc_historic (
    version TEXT,
    b_likely_occ_desc TEXT,
    b_large_alt_reduction TEXT,
    b_nonres_with_units TEXT,
    units_co_prop_mismatch TEXT,
    partially_complete TEXT,
    units_init_null TEXT,
    units_prop_null TEXT,
    units_res_accessory TEXT,
    outlier_demo_20plus TEXT,
    outlier_nb_500plus TEXT,
    outlier_top_alt_increase TEXT,
    dup_bbl_address_units TEXT,
    dup_bbl_address TEXT,
    inactive_with_update TEXT,
    no_work_job TEXT,
    geo_water TEXT,
    geo_taxlot TEXT,
    geo_null_latlong TEXT,
    geo_null_boundary TEXT,
    invalid_date_filed TEXT,
    invalid_date_lastupdt TEXT,
    invalid_date_statusd TEXT,
    invalid_date_statusp TEXT,
    invalid_date_statusr TEXT,
    invalid_date_statusx TEXT,
    incomp_tract_home TEXT,
    dem_nb_overlap TEXT
);
