/** QAQC
    b_large_alt_reduction
    outlier_nb_500plus
    outlier_demo_20plus
    outlier_top_alt_increase
**/

DROP TABLE IF EXISTS UNITS_QAQC;
WITH

JOBNUMBER_LARGE_ALT AS (
    SELECT JOB_NUMBER
    FROM UNITS_DEVDB
    WHERE
        JOB_TYPE = 'Alteration'
        AND CLASSA_NET::numeric < -5
),

JOBNUMBER_LARGE_NB AS (
    SELECT JOB_NUMBER
    FROM UNITS_DEVDB
    WHERE
        JOB_TYPE = 'New Building'
        AND CLASSA_PROP::numeric > 499
),

JOBNUMBER_LARGE_DEMO AS (
    SELECT JOB_NUMBER
    FROM UNITS_DEVDB
    WHERE
        JOB_TYPE = 'Demolition'
        AND CLASSA_INIT::numeric > 19
),

JOBNUMBER_TOP_ALT_INC AS (
    SELECT JOB_NUMBER
    FROM UNITS_DEVDB
    WHERE
        JOB_TYPE = 'Alteration'
        AND CLASSA_NET IS NOT NULL
    ORDER BY CLASSA_NET DESC
    LIMIT 20
),

JOBNUMBER_TOP_ALT_DEC AS (
    SELECT JOB_NUMBER
    FROM UNITS_DEVDB
    WHERE
        JOB_TYPE = 'Alteration'
        AND CLASSA_NET IS NOT NULL
    ORDER BY CLASSA_NET ASC
    LIMIT 20
)

SELECT
    A.*,
    (CASE
        WHEN A.JOB_NUMBER IN (SELECT JOB_NUMBER FROM JOBNUMBER_LARGE_ALT) THEN 1
        ELSE 0
    END) AS B_LARGE_ALT_REDUCTION,
    (CASE
        WHEN A.JOB_NUMBER IN (SELECT JOB_NUMBER FROM JOBNUMBER_LARGE_NB) THEN 1
        ELSE 0
    END) AS OUTLIER_NB_500PLUS,
    (CASE
        WHEN A.JOB_NUMBER IN (SELECT JOB_NUMBER FROM JOBNUMBER_LARGE_DEMO) THEN 1
        ELSE 0
    END) AS OUTLIER_DEMO_20PLUS,
    (CASE
        WHEN A.JOB_NUMBER IN (SELECT JOB_NUMBER FROM JOBNUMBER_TOP_ALT_INC) THEN 1
        ELSE 0
    END) AS OUTLIER_TOP_ALT_INCREASE

INTO UNITS_QAQC
FROM _INIT_QAQC AS A;
