/*
Alphabetize QAQC table for export
*/

DROP TABLE IF EXISTS FINAL_QAQC;
SELECT
    A.JOB_NUMBER,
    A.B_LIKELY_OCC_DESC,
    A.B_LARGE_ALT_REDUCTION,
    A.B_NONRES_WITH_UNITS,
    A.UNITS_CO_PROP_MISMATCH,
    A.PARTIALLY_COMPLETE,
    A.UNITS_INIT_NULL,
    A.UNITS_PROP_NULL,
    A.UNITS_RES_ACCESSORY,
    A.OUTLIER_DEMO_20PLUS,
    A.OUTLIER_NB_500PLUS,
    A.OUTLIER_TOP_ALT_INCREASE,
    A.DUP_BBL_ADDRESS_UNITS,
    A.DUP_BBL_ADDRESS,
    A.INACTIVE_WITH_UPDATE,
    A.NO_WORK_JOB,
    B.GEO_WATER,
    B.GEO_TAXLOT,
    B.GEO_NULL_LATLONG,
    B.GEO_NULL_BOUNDARY,
    A.INVALID_DATE_FILED,
    A.INVALID_DATE_LASTUPDT,
    A.INVALID_DATE_STATUSD,
    A.INVALID_DATE_STATUSP,
    A.INVALID_DATE_STATUSR,
    A.INVALID_DATE_STATUSX,
    A.INCOMP_TRACT_HOME,
    A.DEM_NB_OVERLAP
INTO FINAL_QAQC
FROM MID_QAQC AS A
LEFT JOIN GEO_QAQC AS B
    ON A.JOB_NUMBER = B.JOB_NUMBER;
