SELECT
    "Project_Id" AS project_id,
    "All_ZAP_BBLs" AS bbls,
    "Project_Status_Start_Date"::text,
    "Project_Status_End_Date"::text,
    "Project_Name"::text,
    "Applicant_Type"::text,
    "CEQR_Complexity"::text,
    "ULURP_/_Non_ULURP"::text,
    "System_Lead_Action"::text,
    "ZR_Section_Number"::text,
    "Certified/Referred"::text,
    "Validated_City_Council_Districts"::text,
    "CEQR_Type"::text,
    "Lead_Agency"::text,
    "Lead_Division"::text,
    "Lead_Planner"::text,
    "Major_Initiative"::text,
    "Current_Milestone"::text,
    "Current_Milestone_Actual_Start_Date_(Used_for_PCF)"::text,
    "Project_Status"::text,
    "Project_Brief"::text,
    "EAS_/_EIS"::text,
    "Pre_Cert_Start_Date"::text,
    "Borough"::text,
    "Last_Milestone"::text,
    "Last_Milestone_Date"::text,
    "Validated_Community_Districts"::text
FROM {{ source("recipe_sources", "dcp_projectbbls_cy") }}
