"""Autogenerated by generate_pydantic_xml_classes.py
Source XML: MapPLUTO_UNCLIPPED_as_iso.shp.xml
Do not edit directly.
"""

from pydantic_xml import BaseXmlModel, element, attr


class Charsetcd(BaseXmlModel, tag="CharSetCd"):
    value: str | None = attr(name="value", default=None)


class Consts(BaseXmlModel, tag="Consts"):
    use_limit: str | None = element(tag="useLimit", text=True, default=None)


class Data(BaseXmlModel, tag="Data"):
    esri_property_type: str | None = attr(name="EsriPropertyType", default=None)
    value: str | None = None


class Geoobjtypcd(BaseXmlModel, tag="GeoObjTypCd"):
    value: str | None = attr(name="value", default=None)
    sync: str | None = attr(name="Sync", default=None)


class Presformcd(BaseXmlModel, tag="PresFormCd"):
    value: str | None = attr(name="value", default=None)
    sync: str | None = attr(name="Sync", default=None)


class Scopecd(BaseXmlModel, tag="ScopeCd"):
    value: str | None = attr(name="value", default="005")


class Spatreptypcd(BaseXmlModel, tag="SpatRepTypCd"):
    value: str | None = attr(name="value", default=None)
    sync: str | None = attr(name="Sync", default=None)


class Thumbnail(BaseXmlModel, tag="Thumbnail"):
    data: "Data" = element(tag="Data", default_factory=lambda: Data())


class Binary(BaseXmlModel, tag="Binary"):
    thumbnail: "Thumbnail" = element(
        tag="Thumbnail", default_factory=lambda: Thumbnail()
    )


class Topolevcd(BaseXmlModel, tag="TopoLevCd"):
    value: str | None = attr(name="value", default=None)
    sync: str | None = attr(name="Sync", default=None)


class Atprecis(BaseXmlModel, tag="atprecis"):
    sync: str | None = attr(name="Sync", default=None)
    value: int | None = None


class Attalias(BaseXmlModel, tag="attalias"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Attrdef(BaseXmlModel, tag="attrdef"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Attrdefs(BaseXmlModel, tag="attrdefs"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Attrlabl(BaseXmlModel, tag="attrlabl"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Attrtype(BaseXmlModel, tag="attrtype"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Attscale(BaseXmlModel, tag="attscale"):
    sync: str | None = attr(name="Sync", default=None)
    value: int | None = None


class Attwidth(BaseXmlModel, tag="attwidth"):
    sync: str | None = attr(name="Sync", default=None)
    value: int | None = None


class Countrycode(BaseXmlModel, tag="countryCode"):
    value: str | None = attr(name="value", default=None)
    sync: str | None = attr(name="Sync", default=None)


class Csunits(BaseXmlModel, tag="csUnits"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Datachar(BaseXmlModel, tag="dataChar"):
    char_set_cd: "Charsetcd" = element(
        tag="CharSetCd", default_factory=lambda: Charsetcd()
    )


class Eastbl(BaseXmlModel, tag="eastBL"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Efeacnt(BaseXmlModel, tag="efeacnt"):
    sync: str | None = attr(name="Sync", default=None)
    value: int | None = None


class Efeageom(BaseXmlModel, tag="efeageom"):
    code: int | None = attr(name="code", default=None)
    sync: str | None = attr(name="Sync", default=None)


class Efeatyp(BaseXmlModel, tag="efeatyp"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Enttypc(BaseXmlModel, tag="enttypc"):
    sync: str | None = attr(name="Sync", default=None)
    value: int | None = None


class Enttypl(BaseXmlModel, tag="enttypl"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Enttypt(BaseXmlModel, tag="enttypt"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Enttyp(BaseXmlModel, tag="enttyp"):
    enttypl: "Enttypl" = element(tag="enttypl", default_factory=lambda: Enttypl())
    enttypt: "Enttypt" = element(tag="enttypt", default_factory=lambda: Enttypt())
    enttypc: "Enttypc" = element(tag="enttypc", default_factory=lambda: Enttypc())


class Envirdesc(BaseXmlModel, tag="envirDesc"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Esritopo(BaseXmlModel, tag="esritopo"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Extypecode(BaseXmlModel, tag="exTypeCode"):
    sync: str | None = attr(name="Sync", default=None)
    value: int | None = None


class Formatname(BaseXmlModel, tag="formatName"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Distformat(BaseXmlModel, tag="distFormat"):
    format_name: "Formatname" = element(
        tag="formatName", default_factory=lambda: Formatname()
    )


class Geoobjcnt(BaseXmlModel, tag="geoObjCnt"):
    sync: str | None = attr(name="Sync", default=None)
    value: int | None = None


class Geoobjtyp(BaseXmlModel, tag="geoObjTyp"):
    geo_obj_typ_cd: "Geoobjtypcd" = element(
        tag="GeoObjTypCd", default_factory=lambda: Geoobjtypcd()
    )


class Geogcsn(BaseXmlModel, tag="geogcsn"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Geometobjs(BaseXmlModel, tag="geometObjs"):
    name: str | None = attr(name="Name", default=None)
    geo_obj_typ: "Geoobjtyp" = element(
        tag="geoObjTyp", default_factory=lambda: Geoobjtyp()
    )
    geo_obj_cnt: "Geoobjcnt" = element(
        tag="geoObjCnt", default_factory=lambda: Geoobjcnt()
    )


class Idcodespace(BaseXmlModel, tag="idCodeSpace"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Idversion(BaseXmlModel, tag="idVersion"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Identcode(BaseXmlModel, tag="identCode"):
    code: int | None = attr(name="code", default=None)
    sync: str | None = attr(name="Sync", default=None)


class Imscontenttype(BaseXmlModel, tag="imsContentType"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Itemname(BaseXmlModel, tag="itemName"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Itemsize(BaseXmlModel, tag="itemSize"):
    sync: str | None = attr(name="Sync", default=None)
    value: float | None = None


class Languagecode(BaseXmlModel, tag="languageCode"):
    value: str | None = attr(name="value", default=None)
    sync: str | None = attr(name="Sync", default=None)


class Datalang(BaseXmlModel, tag="dataLang"):
    language_code: "Languagecode" = element(
        tag="languageCode", default_factory=lambda: Languagecode()
    )
    country_code: "Countrycode" = element(
        tag="countryCode", default_factory=lambda: Countrycode()
    )


class Linkage(BaseXmlModel, tag="linkage"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Linrefer(BaseXmlModel, tag="linrefer"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Mdchar(BaseXmlModel, tag="mdChar"):
    char_set_cd: "Charsetcd" = element(
        tag="CharSetCd", default_factory=lambda: Charsetcd()
    )


class Mddatest(BaseXmlModel, tag="mdDateSt"):
    sync: str | None = attr(name="Sync", default="TRUE")
    value: int | None = None


class Mdhrlv(BaseXmlModel, tag="mdHrLv"):
    scope_cd: "Scopecd" = element(tag="ScopeCd", default_factory=lambda: Scopecd())


class Mdlang(BaseXmlModel, tag="mdLang"):
    language_code: "Languagecode" = element(
        tag="languageCode", default_factory=lambda: Languagecode()
    )
    country_code: "Countrycode" = element(
        tag="countryCode", default_factory=lambda: Countrycode()
    )


class Northbl(BaseXmlModel, tag="northBL"):
    sync: str | None = attr(name="Sync", default=None)
    value: float | None = None


class Otherkeys(BaseXmlModel, tag="otherKeys"):
    keyword: list[str] | None = element(tag="keyword", text=True, default_factory=list)


class Pexml(BaseXmlModel, tag="peXml"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Presform(BaseXmlModel, tag="presForm"):
    pres_form_cd: "Presformcd" = element(
        tag="PresFormCd", default_factory=lambda: Presformcd()
    )


class Idcitation(BaseXmlModel, tag="idCitation"):
    res_title: str | None = element(tag="resTitle", text=True, default=None)
    pres_form: "Presform" = element(tag="presForm", default_factory=lambda: Presform())


class Projcsn(BaseXmlModel, tag="projcsn"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Protocol(BaseXmlModel, tag="protocol"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Itemlocation(BaseXmlModel, tag="itemLocation"):
    linkage: "Linkage" = element(tag="linkage", default_factory=lambda: Linkage())
    protocol: "Protocol" = element(tag="protocol", default_factory=lambda: Protocol())


class Refsysid(BaseXmlModel, tag="refSysID"):
    ident_code: "Identcode" = element(
        tag="identCode", default_factory=lambda: Identcode()
    )
    id_code_space: "Idcodespace" = element(
        tag="idCodeSpace", default_factory=lambda: Idcodespace()
    )
    id_version: "Idversion" = element(
        tag="idVersion", default_factory=lambda: Idversion()
    )


class Refsystem(BaseXmlModel, tag="RefSystem"):
    ref_sys_id: "Refsysid" = element(tag="refSysID", default_factory=lambda: Refsysid())


class Refsysinfo(BaseXmlModel, tag="refSysInfo"):
    ref_system: "Refsystem" = element(
        tag="RefSystem", default_factory=lambda: Refsystem()
    )


class Resconst(BaseXmlModel, tag="resConst"):
    consts: "Consts" = element(tag="Consts", default_factory=lambda: Consts())


class Scalerange(BaseXmlModel, tag="scaleRange"):
    min_scale: str | None = element(tag="minScale", text=True, default="150000000")
    max_scale: str | None = element(tag="maxScale", text=True, default="5000")


class Searchkeys(BaseXmlModel, tag="searchKeys"):
    keyword: list[str] | None = element(tag="keyword", text=True, default_factory=list)


class Southbl(BaseXmlModel, tag="southBL"):
    sync: str | None = attr(name="Sync", default=None)
    value: float | None = None


class Spatrptype(BaseXmlModel, tag="spatRpType"):
    spat_rep_typ_cd: "Spatreptypcd" = element(
        tag="SpatRepTypCd", default_factory=lambda: Spatreptypcd()
    )


class Spindex(BaseXmlModel, tag="spindex"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Esriterm(BaseXmlModel, tag="esriterm"):
    name: str | None = attr(name="Name", default=None)
    efeatyp: "Efeatyp" = element(tag="efeatyp", default_factory=lambda: Efeatyp())
    efeageom: "Efeageom" = element(tag="efeageom", default_factory=lambda: Efeageom())
    esritopo: "Esritopo" = element(tag="esritopo", default_factory=lambda: Esritopo())
    efeacnt: "Efeacnt" = element(tag="efeacnt", default_factory=lambda: Efeacnt())
    spindex: "Spindex" = element(tag="spindex", default_factory=lambda: Spindex())
    linrefer: "Linrefer" = element(tag="linrefer", default_factory=lambda: Linrefer())


class Ptvctinf(BaseXmlModel, tag="ptvctinf"):
    esriterm: "Esriterm" = element(tag="esriterm", default_factory=lambda: Esriterm())


class Spdoinfo(BaseXmlModel, tag="spdoinfo"):
    ptvctinf: "Ptvctinf" = element(tag="ptvctinf", default_factory=lambda: Ptvctinf())


class Toplvl(BaseXmlModel, tag="topLvl"):
    topo_lev_cd: "Topolevcd" = element(
        tag="TopoLevCd", default_factory=lambda: Topolevcd()
    )


class Vectspatrep(BaseXmlModel, tag="VectSpatRep"):
    geomet_objs: "Geometobjs" = element(
        tag="geometObjs", default_factory=lambda: Geometobjs()
    )
    top_lvl: "Toplvl" = element(tag="topLvl", default_factory=lambda: Toplvl())


class Spatrepinfo(BaseXmlModel, tag="spatRepInfo"):
    vect_spat_rep: "Vectspatrep" = element(
        tag="VectSpatRep", default_factory=lambda: Vectspatrep()
    )


class Transsize(BaseXmlModel, tag="transSize"):
    sync: str | None = attr(name="Sync", default=None)
    value: float | None = None


class Disttranops(BaseXmlModel, tag="distTranOps"):
    trans_size: "Transsize" = element(
        tag="transSize", default_factory=lambda: Transsize()
    )


class Distinfo(BaseXmlModel, tag="distInfo"):
    dist_format: "Distformat" = element(
        tag="distFormat", default_factory=lambda: Distformat()
    )
    dist_tran_ops: "Disttranops" = element(
        tag="distTranOps", default_factory=lambda: Disttranops()
    )


class Type(BaseXmlModel, tag="type"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Coordref(BaseXmlModel, tag="coordRef"):
    type: "Type" = element(tag="type", default_factory=lambda: Type())
    geogcsn: "Geogcsn" = element(tag="geogcsn", default_factory=lambda: Geogcsn())
    cs_units: "Csunits" = element(tag="csUnits", default_factory=lambda: Csunits())
    projcsn: "Projcsn" = element(tag="projcsn", default_factory=lambda: Projcsn())
    pe_xml: "Pexml" = element(tag="peXml", default_factory=lambda: Pexml())


class Udom(BaseXmlModel, tag="udom"):
    sync: str | None = attr(name="Sync", default=None)
    value: str | None = None


class Attrdomv(BaseXmlModel, tag="attrdomv"):
    udom: "list[Udom] | None" = element(tag="udom", default_factory=list)


class Attr(BaseXmlModel, tag="attr"):
    attrlabl: "list[Attrlabl] | None" = element(tag="attrlabl", default_factory=list)
    attalias: "list[Attalias] | None" = element(tag="attalias", default_factory=list)
    attrtype: "list[Attrtype] | None" = element(tag="attrtype", default_factory=list)
    attwidth: "list[Attwidth] | None" = element(tag="attwidth", default_factory=list)
    atprecis: "list[Atprecis] | None" = element(tag="atprecis", default_factory=list)
    attscale: "list[Attscale] | None" = element(tag="attscale", default_factory=list)
    attrdef: "list[Attrdef] | None" = element(tag="attrdef", default_factory=list)
    attrdefs: "list[Attrdefs] | None" = element(tag="attrdefs", default_factory=list)
    attrdomv: "list[Attrdomv] | None" = element(tag="attrdomv", default_factory=list)


class Detailed(BaseXmlModel, tag="detailed"):
    name: str | None = attr(name="Name", default=None)
    enttyp: "Enttyp" = element(tag="enttyp", default_factory=lambda: Enttyp())
    attr: "list[Attr] | None" = element(tag="attr", default_factory=list)


class Eainfo(BaseXmlModel, tag="eainfo"):
    detailed: "Detailed" = element(tag="detailed", default_factory=lambda: Detailed())


class Westbl(BaseXmlModel, tag="westBL"):
    sync: str | None = attr(name="Sync", default=None)
    value: float | None = None


class Geobndbox(BaseXmlModel, tag="GeoBndBox"):
    esri_extent_type: str | None = attr(name="esriExtentType", default=None)
    ex_type_code: "Extypecode" = element(
        tag="exTypeCode", default_factory=lambda: Extypecode()
    )
    west_bl: "Westbl" = element(tag="westBL", default_factory=lambda: Westbl())
    east_bl: "Eastbl" = element(tag="eastBL", default_factory=lambda: Eastbl())
    north_bl: "Northbl" = element(tag="northBL", default_factory=lambda: Northbl())
    south_bl: "Southbl" = element(tag="southBL", default_factory=lambda: Southbl())


class Geoele(BaseXmlModel, tag="geoEle"):
    geo_bnd_box: "Geobndbox" = element(
        tag="GeoBndBox", default_factory=lambda: Geobndbox()
    )


class Dataext(BaseXmlModel, tag="dataExt"):
    geo_ele: "Geoele" = element(tag="geoEle", default_factory=lambda: Geoele())


class Dataidinfo(BaseXmlModel, tag="dataIdInfo"):
    id_citation: "Idcitation" = element(
        tag="idCitation", default_factory=lambda: Idcitation()
    )
    id_abs: str | None = element(tag="idAbs", text=True, default=None)
    id_purp: str | None = element(tag="idPurp", text=True, default=None)
    id_credit: str | None = element(tag="idCredit", text=True, default=None)
    other_keys: "Otherkeys" = element(
        tag="otherKeys", default_factory=lambda: Otherkeys()
    )
    search_keys: "Searchkeys" = element(
        tag="searchKeys", default_factory=lambda: Searchkeys()
    )
    res_const: "Resconst" = element(tag="resConst", default_factory=lambda: Resconst())
    data_char: "Datachar" = element(tag="dataChar", default_factory=lambda: Datachar())
    envir_desc: "Envirdesc" = element(
        tag="envirDesc", default_factory=lambda: Envirdesc()
    )
    data_lang: "Datalang" = element(tag="dataLang", default_factory=lambda: Datalang())
    spat_rp_type: "Spatrptype" = element(
        tag="spatRpType", default_factory=lambda: Spatrptype()
    )
    data_ext: "Dataext" = element(tag="dataExt", default_factory=lambda: Dataext())


class Nativeextbox(BaseXmlModel, tag="nativeExtBox"):
    west_bl: "Westbl" = element(tag="westBL", default_factory=lambda: Westbl())
    east_bl: "Eastbl" = element(tag="eastBL", default_factory=lambda: Eastbl())
    south_bl: "Southbl" = element(tag="southBL", default_factory=lambda: Southbl())
    north_bl: "Northbl" = element(tag="northBL", default_factory=lambda: Northbl())
    ex_type_code: "Extypecode" = element(
        tag="exTypeCode", default_factory=lambda: Extypecode()
    )


class Itemprops(BaseXmlModel, tag="itemProps"):
    item_name: "Itemname" = element(tag="itemName", default_factory=lambda: Itemname())
    ims_content_type: "Imscontenttype" = element(
        tag="imsContentType", default_factory=lambda: Imscontenttype()
    )
    native_ext_box: "Nativeextbox" = element(
        tag="nativeExtBox", default_factory=lambda: Nativeextbox()
    )
    item_size: "Itemsize" = element(tag="itemSize", default_factory=lambda: Itemsize())
    item_location: "Itemlocation" = element(
        tag="itemLocation", default_factory=lambda: Itemlocation()
    )


class Dataproperties(BaseXmlModel, tag="DataProperties"):
    item_props: "Itemprops" = element(
        tag="itemProps", default_factory=lambda: Itemprops()
    )
    coord_ref: "Coordref" = element(tag="coordRef", default_factory=lambda: Coordref())


class Esri(BaseXmlModel, tag="Esri"):
    crea_date: str | None = element(tag="CreaDate", text=True, default=None)
    crea_time: str | None = element(tag="CreaTime", text=True, default=None)
    arc_gis_format: float | None = element(tag="ArcGISFormat", text=True, default=1.0)
    sync_once: str | None = element(tag="SyncOnce", text=True, default="TRUE")
    data_properties: "Dataproperties" = element(
        tag="DataProperties", default_factory=lambda: Dataproperties()
    )
    sync_date: str | None = element(tag="SyncDate", text=True, default=None)
    sync_time: str | None = element(tag="SyncTime", text=True, default=None)
    mod_date: str | None = element(tag="ModDate", text=True, default=None)
    mod_time: str | None = element(tag="ModTime", text=True, default=None)
    scale_range: "Scalerange" = element(
        tag="scaleRange", default_factory=lambda: Scalerange()
    )
    arc_gis_profile: str | None = element(
        tag="ArcGISProfile", text=True, default="ISO19139"
    )


class Metadata(BaseXmlModel, tag="metadata", skip_empty=True):
    lang: str | None = attr(
        name="{http://www.w3.org/XML/1998/namespace}lang", default="en"
    )
    esri: "Esri" = element(tag="Esri", default_factory=lambda: Esri())
    md_char: "Mdchar" = element(tag="mdChar", default_factory=lambda: Mdchar())
    md_hr_lv: "Mdhrlv" = element(tag="mdHrLv", default_factory=lambda: Mdhrlv())
    md_hr_lv_name: str | None = element(tag="mdHrLvName", text=True, default=None)
    md_stan_name: str | None = element(
        tag="mdStanName", text=True, default="ArcGIS Metadata"
    )
    md_stan_ver: float | None = element(tag="mdStanVer", text=True, default=1.0)
    data_id_info: "Dataidinfo" = element(
        tag="dataIdInfo", default_factory=lambda: Dataidinfo()
    )
    md_lang: "Mdlang" = element(tag="mdLang", default_factory=lambda: Mdlang())
    dist_info: "Distinfo" = element(tag="distInfo", default_factory=lambda: Distinfo())
    ref_sys_info: "Refsysinfo" = element(
        tag="refSysInfo", default_factory=lambda: Refsysinfo()
    )
    spat_rep_info: "Spatrepinfo" = element(
        tag="spatRepInfo", default_factory=lambda: Spatrepinfo()
    )
    spdoinfo: "Spdoinfo" = element(tag="spdoinfo", default_factory=lambda: Spdoinfo())
    eainfo: "Eainfo" = element(tag="eainfo", default_factory=lambda: Eainfo())
    md_date_st: "Mddatest" = element(tag="mdDateSt", default_factory=lambda: Mddatest())
    binary: "Binary" = element(tag="Binary", default_factory=lambda: Binary())
