name: EDDE
product: db-eddt
inputs:
  dataset_defaults:
    file_type: parquet
    destination: file
  datasets:
# From the spreadsheet
  # Ingested
  - name: edde
    version: latest
    source: edm.publishing.published

  - name: doi_evictions_geocoded # 3.09 (geocoded version)
    version: latest
  - name: hpd_hny_units_by_building # 3.11, 4.02
    version: '20260519'
  - name: dcp_housing # 4.01
    version: '25Q4'
  - name: lpc_historic_district_areas # 4.03
    version: '20260202'
  - name: dhs_shelterd_indiv_by_comm_dist # 3.1
    version: 20260504

  - name: dcp_pumas2020
    version: '20260526'
  - name: dcp_population_cd_puma_crosswalk_2020
    version: '2025'
  - name: dcp_population_nta_puma_crosswalk_2020
    version: '2025'

  # A decade of traffic injury data # 5.15
  - name: dcp_dot_trafficinjuries
    version: 2010
    file_type: csv
  - name: dcp_dot_trafficinjuries
    version: 2011
    file_type: csv
  - name: dcp_dot_trafficinjuries
    version: 2012
    file_type: csv
  - name: dcp_dot_trafficinjuries
    version: 2013
    file_type: csv
  - name: dcp_dot_trafficinjuries
    version: 2014
    file_type: csv
  - name: dcp_dot_trafficinjuries
    version: 2015
    file_type: csv
  - name: dcp_dot_trafficinjuries
    version: 2016
    file_type: csv
  - name: dcp_dot_trafficinjuries
    version: 2017
    file_type: csv
  - name: dcp_dot_trafficinjuries
    version: 2018
    file_type: csv
  - name: dcp_dot_trafficinjuries
    version: 2019
    file_type: csv
  - name: dcp_dot_trafficinjuries
    version: 2020
    file_type: csv

custom:
  # Build configuration
  EDDE_VERSION_PREV: "2025-05-30"
  CENSUS_BASE_YEAR: "2000"
  ACS_PREV_YEAR_BAND: "0812"
  ACS_CURRENT_YEAR_BAND: "2024"
  HOUSING_DATABASE_QUARTER: "2024 Q4"

  ignored_indicators:
    - health_diabetes
    - health_self_reported
    - health_selfreportedhealth

  health_mortality:
    latest_year: "1620"
    puma_baseline_years: ["0004", "1014"]
    baseline_years: ["2000", "2010"]

  traffic_fatalities:
    year_ranges:
      "1014": [2010, 2015]
      "1620": [2016, 2021]

  dhs_shelter:
    years: ["2020", "2025"]

stage_config:
  builds.build:
    commands:
      - name: build
        run: build
        command_type: python
      - name: qa
        run: qa.proto_qa
        command_type: python
      - name: package
        run: packager
        command_type: python
    destination: edm.publishing.builds
    destination_key: db-eddt
    connector_args:
      - name: acl
        value: public-read
