DROP TABLE pluto_pts;
DROP TABLE pluto_input_cama_dof;
DROP TABLE pluto_input_cama;
DROP TABLE pluto_input_geocodes;
DROP TABLE dof_dtm;
DROP TABLE pluto_dtm;
DROP TABLE validdtm;
DROP TABLE lotzoneper;
DROP TABLE lotzoneperorder;
