DROP TABLE IF EXISTS :TABLE;
SELECT
    a.borough AS "Borough",
    a.block::numeric::integer AS "Block",
    a.lot::smallint AS "Lot",
    a.cd::smallint AS "CD",
    a.bct2020 AS "BCT2020",
    a.bctcb2020 AS "BCTCB2020",
    a.ct2010 AS "CT2010",
    a.cb2010 AS "CB2010",
    a.schooldist AS "SchoolDist",
    a.council::smallint AS "Council",
    a.zipcode::numeric::integer AS "ZipCode",
    a.firecomp AS "FireComp",
    a.policeprct::smallint AS "PolicePrct",
    a.healthcenterdistrict::smallint AS "HealthCenterDistrict",
    a.healtharea::smallint AS "HealthArea",
    a.sanitboro AS "Sanitboro",
    a.sanitdistrict AS "SanitDistrict",
    a.sanitsub AS "SanitSub",
    a.address AS "Address",
    a.zonedist1 AS "ZoneDist1",
    a.zonedist2 AS "ZoneDist2",
    a.zonedist3 AS "ZoneDist3",
    a.zonedist4 AS "ZoneDist4",
    a.overlay1 AS "Overlay1",
    a.overlay2 AS "Overlay2",
    a.spdist1 AS "SPDist1",
    a.spdist2 AS "SPDist2",
    a.spdist3 AS "SPDist3",
    a.ltdheight AS "LtdHeight",
    a.splitzone AS "SplitZone",
    a.bldgclass AS "BldgClass",
    a.landuse AS "LandUse",
    a.easements::smallint AS "Easements",
    a.ownertype AS "OwnerType",
    a.ownername AS "OwnerName",
    a.lotarea::numeric::integer AS "LotArea",
    a.bldgarea::numeric::integer AS "BldgArea",
    a.comarea::numeric::integer AS "ComArea",
    a.resarea::numeric::integer AS "ResArea",
    a.officearea::numeric::integer AS "OfficeArea",
    a.retailarea::numeric::integer AS "RetailArea",
    a.garagearea::numeric::integer AS "GarageArea",
    a.strgearea::numeric::integer AS "StrgeArea",
    a.factryarea::numeric::integer AS "FactryArea",
    a.otherarea::numeric::integer AS "OtherArea",
    a.areasource AS "AreaSource",
    a.numbldgs::numeric::integer AS "NumBldgs",
    a.numfloors AS "NumFloors",
    a.unitsres::numeric::integer AS "UnitsRes",
    a.unitstotal::numeric::integer AS "UnitsTotal",
    a.lotfront AS "LotFront",
    a.lotdepth AS "LotDepth",
    a.bldgfront AS "BldgFront",
    a.bldgdepth AS "BldgDepth",
    a.ext AS "Ext",
    a.proxcode AS "ProxCode",
    a.irrlotcode AS "IrrLotCode",
    a.lottype AS "LotType",
    a.bsmtcode AS "BsmtCode",
    a.assessland AS "AssessLand",
    a.assesstot AS "AssessTot",
    a.exempttot AS "ExemptTot",
    a.yearbuilt::smallint AS "YearBuilt",
    a.yearalter1::smallint AS "YearAlter1",
    a.yearalter2::smallint AS "YearAlter2",
    a.histdist AS "HistDist",
    a.landmark AS "Landmark",
    a.builtfar AS "BuiltFAR",
    a.residfar AS "ResidFAR",
    a.commfar AS "CommFAR",
    a.facilfar AS "FacilFAR",
    a.borocode::numeric::integer AS "BoroCode",
    a.bbl AS "BBL",
    a.condono::numeric::integer AS "CondoNo",
    a.tract2010 AS "Tract2010",
    a.xcoord::numeric::integer AS "XCoord",
    a.ycoord::numeric::integer AS "YCoord",
    a.zonemap AS "ZoneMap",
    a.zmcode AS "ZMCode",
    a.sanborn AS "Sanborn",
    a.taxmap AS "TaxMap",
    a.edesignum AS "EDesigNum",
    a.appbbl AS "APPBBL",
    a.appdate AS "APPDate",
    a.plutomapid AS "PLUTOMapID",
    a.firm07_flag AS "FIRM07_FLAG",
    a.pfirm15_flag AS "PFIRM15_FLAG",
    a.version AS "Version",
    a.dcpedited AS "DCPEdited",
    a.latitude AS "Latitude",
    a.longitude AS "Longitude",
    a.notes AS "Notes",
    round(ST_Length(b.:GEOM)::numeric, 11)::numeric(19, 7) AS "Shape_Leng",
    round(ST_Area(b.:GEOM)::numeric, 11)::numeric(19, 7) AS "Shape_Area",
    ST_MakeValid(b.:GEOM) AS geom
INTO :TABLE
FROM export_pluto AS a, pluto_geom AS b
WHERE
    b.:GEOM IS NOT NULL AND NOT ST_IsEmpty(b.:GEOM)
    AND a.bbl::bigint = b.bbl::bigint;

ALTER TABLE :TABLE ALTER COLUMN "Borough" SET NOT NULL;
ALTER TABLE :TABLE ALTER COLUMN "Block" SET NOT NULL;
ALTER TABLE :TABLE ALTER COLUMN "Lot" SET NOT NULL;
ALTER TABLE :TABLE ALTER COLUMN "BBL" SET NOT NULL;
ALTER TABLE :TABLE ALTER COLUMN "BoroCode" SET NOT NULL;
