DROP TABLE IF EXISTS export_pluto;
SELECT
    borough::varchar(2),
    trim(block)::numeric(10, 0) AS block,
    lot::numeric(5, 0),
    cd::numeric(5, 0),
    bct2020::varchar(7),
    bctcb2020::varchar(11),
    ct2010::varchar(7),
    cb2010::varchar(5),
    schooldist::varchar(3),
    council::numeric(5, 0),
    zipcode::numeric(10, 0),
    firecomp::varchar(4),
    policeprct::numeric(5, 0),
    healthcenterdistrict::numeric(5, 0),
    healtharea::numeric(5, 0),
    sanitboro::varchar(2),
    sanitdistrict::varchar(2),
    sanitsub::varchar(2),
    address::varchar(39),
    zonedist1::varchar(12),
    zonedist2::varchar(12),
    zonedist3::varchar(12),
    zonedist4::varchar(12),
    overlay1::varchar(4),
    overlay2::varchar(4),
    spdist1::varchar(12),
    spdist2::varchar(12),
    spdist3::varchar(12),
    ltdheight::varchar(5),
    splitzone::varchar(1),
    bldgclass::varchar(2),
    landuse::varchar(2),
    easements::numeric(5, 0),
    ownertype::varchar(1),
    ownername::varchar(85),
    lotarea::numeric(10, 0),
    bldgarea::numeric(10, 0),
    comarea::numeric(10, 0),
    resarea::numeric(10, 0),
    officearea::numeric(10, 0),
    retailarea::numeric(10, 0),
    garagearea::numeric(10, 0),
    strgearea::numeric(10, 0),
    factryarea::numeric(10, 0),
    otherarea::numeric(10, 0),
    areasource::varchar(1),
    numbldgs::numeric(10, 0),
    numfloors::numeric(19, 7),
    unitsres::numeric(10, 0),
    unitstotal::numeric(10, 0),
    lotfront::numeric(19, 7),
    lotdepth::numeric(19, 7),
    bldgfront::numeric(19, 7),
    bldgdepth::numeric(19, 7),
    ext::varchar(2),
    proxcode::varchar(1),
    irrlotcode::varchar(1),
    lottype::varchar(1),
    bsmtcode::varchar(1),
    assessland::numeric(19, 5),
    assesstot::numeric(19, 5),
    exempttot::numeric(19, 5),
    yearbuilt::numeric(5, 0),
    yearalter1::numeric(5, 0),
    yearalter2::numeric(5, 0),
    histdist::varchar(66),
    landmark::varchar(150),
    builtfar::numeric(19, 11),
    residfar::numeric(19, 11),
    commfar::numeric(19, 11),
    facilfar::numeric(19, 11),
    borocode::numeric(10, 0),
    bbl::numeric(19, 8),
    condono::numeric(10, 0),
    tract2010::varchar(7),
    round(xcoord::numeric)::numeric(10, 0) AS xcoord,
    round(ycoord::numeric)::numeric(10, 0) AS ycoord,
    zonemap::varchar(3),
    zmcode::varchar(1),
    sanborn::varchar(8),
    taxmap::varchar(5),
    edesignum::varchar(5),
    appbbl::numeric(19, 8),
    appdate::varchar(10),
    plutomapid::varchar(1),
    firm07_flag::varchar(1),
    pfirm15_flag::varchar(1),
    version::varchar(6),
    dcpedited::varchar(3),
    latitude::numeric(19, 7),
    longitude::numeric(19, 7),
    notes::varchar(20),
    mih_affordability_option::varchar(50),
    mih_project_name::varchar(50),
    trnstzone::varchar(50),
    affresfar::numeric(19, 11),
    mnffar::numeric(19, 11)
INTO export_pluto
FROM pluto;

DROP TABLE IF EXISTS archive_pluto;
SELECT
    a.*,
    b.clipped_4326 AS geom
INTO archive_pluto
FROM export_pluto AS a
LEFT JOIN pluto_geom AS b
    ON a.bbl::bigint = b.bbl::bigint;

DROP TABLE IF EXISTS unmapped;
SELECT
    a.borough AS "Borough",
    a.block::numeric::integer AS "Block",
    a.lot::smallint AS "Lot",
    a.cd::smallint AS "CD",
    a.bct2020 AS "BCT2020",
    a.bctcb2020 AS "BCTCB2020",
    a.ct2010 AS "CT2010",
    a.cb2010 AS "CB2010",
    a.schooldist AS "SchoolDist",
    a.council::smallint AS "Council",
    a.zipcode::numeric::integer AS "ZipCode",
    a.firecomp AS "FireComp",
    a.policeprct::smallint AS "PolicePrct",
    a.healthcenterdistrict::smallint AS "HealthCenterDistrict",
    a.healtharea::smallint AS "HealthArea",
    a.sanitboro AS "Sanitboro",
    a.sanitdistrict AS "SanitDistrict",
    a.sanitsub AS "SanitSub",
    a.address AS "Address",
    a.zonedist1 AS "ZoneDist1",
    a.zonedist2 AS "ZoneDist2",
    a.zonedist3 AS "ZoneDist3",
    a.zonedist4 AS "ZoneDist4",
    a.overlay1 AS "Overlay1",
    a.overlay2 AS "Overlay2",
    a.spdist1 AS "SPDist1",
    a.spdist2 AS "SPDist2",
    a.spdist3 AS "SPDist3",
    a.ltdheight AS "LtdHeight",
    a.splitzone AS "SplitZone",
    a.bldgclass AS "BldgClass",
    a.landuse AS "LandUse",
    a.easements::smallint AS "Easements",
    a.ownertype AS "OwnerType",
    a.ownername AS "OwnerName",
    a.lotarea::numeric::integer AS "LotArea",
    a.bldgarea::numeric::integer AS "BldgArea",
    a.comarea::numeric::integer AS "ComArea",
    a.resarea::numeric::integer AS "ResArea",
    a.officearea::numeric::integer AS "OfficeArea",
    a.retailarea::numeric::integer AS "RetailArea",
    a.garagearea::numeric::integer AS "GarageArea",
    a.strgearea::numeric::integer AS "StrgeArea",
    a.factryarea::numeric::integer AS "FactryArea",
    a.otherarea::numeric::integer AS "OtherArea",
    a.areasource AS "AreaSource",
    a.numbldgs::numeric::integer AS "NumBldgs",
    a.numfloors AS "NumFloors",
    a.unitsres::numeric::integer AS "UnitsRes",
    a.unitstotal::numeric::integer AS "UnitsTotal",
    a.lotfront AS "LotFront",
    a.lotdepth AS "LotDepth",
    a.bldgfront AS "BldgFront",
    a.bldgdepth AS "BldgDepth",
    a.ext AS "Ext",
    a.proxcode AS "ProxCode",
    a.irrlotcode AS "IrrLotCode",
    a.lottype AS "LotType",
    a.bsmtcode AS "BsmtCode",
    a.assessland AS "AssessLand",
    a.assesstot AS "AssessTot",
    a.exempttot AS "ExemptTot",
    a.yearbuilt::smallint AS "YearBuilt",
    a.yearalter1::smallint AS "YearAlter1",
    a.yearalter2::smallint AS "YearAlter2",
    a.histdist AS "HistDist",
    a.landmark AS "Landmark",
    a.builtfar AS "BuiltFAR",
    a.residfar AS "ResidFAR",
    a.commfar AS "CommFAR",
    a.facilfar AS "FacilFAR",
    a.borocode::numeric::integer AS "BoroCode",
    a.bbl AS "BBL",
    a.condono::numeric::integer AS "CondoNo",
    a.tract2010 AS "Tract2010",
    a.xcoord::numeric::integer AS "XCoord",
    a.ycoord::numeric::integer AS "YCoord",
    a.zonemap AS "ZoneMap",
    a.zmcode AS "ZMCode",
    a.sanborn AS "Sanborn",
    a.taxmap AS "TaxMap",
    a.edesignum AS "EDesigNum",
    a.appbbl AS "APPBBL",
    a.appdate AS "APPDate",
    a.plutomapid AS "PLUTOMapID",
    a.firm07_flag AS "FIRM07_FLAG",
    a.pfirm15_flag AS "PFIRM15_FLAG",
    a.version AS "Version",
    a.dcpedited AS "DCPEdited",
    a.latitude AS "Latitude",
    a.longitude AS "Longitude",
    a.notes AS "Notes",
    a.mih_affordability_option AS "MIHAffOption",
    a.mih_project_name AS "MIHProjectName",
    a.trnstzone AS "TrnstZone",
    a.affresfar AS "AffResFAR",
    a.mnffar AS "ManuFAR"
INTO unmapped
FROM export_pluto AS a
WHERE bbl::bigint IN (
    SELECT bbl::bigint
    FROM pluto
    WHERE geom IS NULL
);

ALTER TABLE unmapped ALTER COLUMN "Borough" SET NOT NULL;
ALTER TABLE unmapped ALTER COLUMN "Block" SET NOT NULL;
ALTER TABLE unmapped ALTER COLUMN "Lot" SET NOT NULL;
ALTER TABLE unmapped ALTER COLUMN "BBL" SET NOT NULL;
ALTER TABLE unmapped ALTER COLUMN "BoroCode" SET NOT NULL;
