name: CEQR
product: db-ceqr
version_strategy: first_of_month

inputs:
  missing_versions_strategy: find_latest

  dataset_defaults:
    file_type: parquet

  datasets:
    - name: dcp_mappluto_wi
    - name: dcp_projects
