[project]
name = "dcpy-app-dagster"
version = "0.0.1"
description = "DCP Data Engineering - Dagster orchestration app"
requires-python = ">=3.11"
dependencies = [
    "dcpy-lifecycle",
    "dcpy-product-metadata",
    "dagster",
    "dagster-webserver",
    "PyYAML",
]

[tool.uv.sources]
dcpy-lifecycle = { workspace = true }
dcpy-product-metadata = { workspace = true }

[tool.uv]
package = false
