
DROP TABLE IF EXISTS _INIT_HPD_historical_units_by_building;
SELECT
    ogc_fid,
    project_id,
    project_name,
    null as project_start_date,
    null as project_completion_date,
    building_id,
    house_number as number,
    street_name as street,
    boro_short_name as borough,
    null as postcode,
    bbl,
    null as bin,
    null as community_board,
    null as council_district,
    null as census_tract,
    null as nta___neighborhood_tabulation_area,
    null as latitude,
    null as longitude,
    null as "latitude_(internal)",
    null as "longitude_(internal)",
    null as building_completion_date,
    reporting_construction_type,
    affordable_units as extended_affordability_only,
    null as prevailing_wage_status,
    null as extremely_low_income_units,
    null as very_low_income_units,
    null as low_income_units,
    null as moderate_income_units,
    null as middle_income_units,
    null as other_income_units,
    null as studio_units,
    null as "1_br_units",
    null as "2_br_units",
    null as "3_br_units",
    null as "4_br_units",
    null as "5_br_units",
    null as "6_br+_units",
    null as unknown_br_units,
    null as counted_rental_units,
    null as counted_homeownership_units,
    null as all_counted_units,
    total_units,
    data_library_version
INTO _INIT_HPD_historical_units_by_building
FROM hpd_historical_units_by_building;
