-- output a diff file with bbls that have changed in any field
CREATE TEMP TABLE tmp (
    dtm_id int,
    boroughcode text,
    taxblock text,
    taxlot text,
    bblnew text,
    zd1new text,
    zd2new text,
    zd3new text,
    zd4new text,
    co1new text,
    co2new text,
    sd1new text,
    sd2new text,
    sd3new text,
    lhdnew text,
    zmnnew text,
    zmcnew text,
    area text,
    inzonechange text,
    bblprev text,
    zd1prev text,
    zd2prev text,
    zd3prev text,
    zd4prev text,
    co1prev text,
    co2prev text,
    sd1prev text,
    sd2prev text,
    sd3prev text,
    lhdprev text,
    zmnprev text,
    zmcprev text
);

\COPY tmp FROM PSTDIN DELIMITER ',' CSV HEADER;

DROP TABLE IF EXISTS qc_bbldiffs;
SELECT
    a.boroughcode,
    a.taxblock,
    a.taxlot,
    a.bblnew,
    a.zd1new,
    a.zd2new,
    a.zd3new,
    a.zd4new,
    a.co1new,
    a.co2new,
    a.sd1new,
    a.sd2new,
    a.sd3new,
    a.lhdnew,
    a.zmnnew,
    a.zmcnew,
    a.area,
    a.inzonechange,
    a.bblprev,
    a.zd1prev,
    a.zd2prev,
    a.zd3prev,
    a.zd4prev,
    a.co1prev,
    a.co2prev,
    a.sd1prev,
    a.sd2prev,
    a.sd3prev,
    a.lhdprev,
    a.zmnprev,
    a.zmcprev,
    b.geom
INTO qc_bbldiffs
FROM tmp AS a
INNER JOIN dof_dtm AS b
    ON a.dtm_id = b.id
