/** QAQC
    inactive_with_update
    partially_complete
**/

DROP TABLE IF EXISTS STATUS_QAQC;
WITH
JOBNUMBER_INACTIVE_UPDATE AS (
    SELECT JOB_NUMBER
    FROM STATUS_DEVDB
    WHERE
        DATE_LASTUPDT >: 'CAPTURE_DATE_PREV'::date
        AND JOB_NUMBER IN (
            SELECT JOB_NUMBER
            FROM _MANUAL_CORRECTIONS
            WHERE
                FIELD = 'job_inactive'
                AND NEW_VALUE ~* 'Inactive'
        )
),

JOBNUMBER_PARTIALLY_COMPLETE AS (
    SELECT JOB_NUMBER
    FROM STATUS_DEVDB
    WHERE JOB_STATUS = '4. Partially Completed Construction'
)

SELECT
    A.*,
    (CASE
        WHEN A.JOB_NUMBER IN (SELECT JOB_NUMBER FROM JOBNUMBER_INACTIVE_UPDATE) THEN 1
        ELSE 0
    END) AS INACTIVE_WITH_UPDATE,
    (CASE
        WHEN A.JOB_NUMBER IN (SELECT JOB_NUMBER FROM JOBNUMBER_PARTIALLY_COMPLETE) THEN 1
        ELSE 0
    END) AS PARTIALLY_COMPLETE
INTO STATUS_QAQC
FROM UNITS_QAQC AS A;
