/*
GEO SPATIAL QAQC
*/

DROP TABLE IF EXISTS GEO_QAQC;
SELECT
    JOB_NUMBER,
    CASE
        WHEN in_water(GEOM)
            THEN 1
        ELSE 0
    END
    AS GEO_WATER,
    CASE
        WHEN get_bbl(GEOM) IS NULL
            THEN 1
        ELSE 0
    END
    AS GEO_TAXLOT,
    CASE
        WHEN
            LONGITUDE IS NULL
            OR LATITUDE IS NULL
            THEN 1
        ELSE 0
    END
    AS GEO_NULL_LATLONG,
    CASE
        WHEN
            GEO_ZIPCODE IS NULL
            OR GEO_BORO IS NULL
            OR GEO_CD IS NULL
            OR GEO_COUNCIL IS NULL
            OR GEO_NTA2020 IS NULL
            OR GEO_NTANAME2020 IS NULL
            OR GEO_CB2020 IS NULL
            OR GEO_CT2020 IS NULL
            OR GEO_CDTA2020 IS NULL
            OR GEO_CDTANAME2020 IS NULL
            OR GEO_CSD IS NULL
            OR GEO_POLICEPRCT IS NULL
            OR GEO_FIREDIVISION IS NULL
            OR GEO_FIREBATTALION IS NULL
            OR GEO_FIRECOMPANY IS NULL
            OR GEO_SCHOOLELMNTRY IS NULL
            OR GEO_SCHOOLMIDDLE IS NULL
            OR GEO_SCHOOLSUBDIST IS NULL
            THEN 1
        ELSE 0
    END
    AS GEO_NULL_BOUNDARY
INTO GEO_QAQC
FROM MID_DEVDB;
