DROP TABLE IF EXISTS cpdb_projects_geom;
CREATE TABLE cpdb_projects_geom AS
SELECT
    a.ccpversion,
    a.maprojid,
    a.magencyacro,
    a.magency,
    a.magencyname,
    a.description,
    a.projectid,
    c.mindate,
    c.maxdate,
    d.typecategory,
    a.plannedcommit_ccnonexempt,
    a.plannedcommit_ccexempt,
    a.plannedcommit_citycost,
    a.plannedcommit_nccstate,
    a.plannedcommit_nccfederal,
    a.plannedcommit_nccother,
    a.plannedcommit_noncitycost,
    a.plannedcommit_total,
    c.spent_total_checkbooknyc,
    e.adopt_ccnonexempt,
    e.adopt_ccexempt,
    e.adopt_citycost,
    e.adopt_nccstate,
    e.adopt_nccfederal,
    e.adopt_nccother,
    e.adopt_noncitycost,
    e.adopt_total,
    e.allocate_ccnonexempt,
    e.allocate_ccexempt,
    e.allocate_citycost,
    e.allocate_nccstate,
    e.allocate_nccfederal,
    e.allocate_nccother,
    e.allocate_noncitycost,
    e.allocate_total,
    e.commit_ccnonexempt,
    e.commit_ccexempt,
    e.commit_citycost,
    e.commit_nccstate,
    e.commit_nccfederal,
    e.commit_nccother,
    e.commit_noncitycost,
    e.commit_total,
    e.spent_ccnonexempt,
    e.spent_ccexempt,
    e.spent_citycost,
    e.spent_nccstate,
    e.spent_nccfederal,
    e.spent_nccother,
    e.spent_noncitycost,
    e.spent_total,
    d.geom
FROM ccp_projects AS a
LEFT JOIN (
    SELECT
        x.maprojid,
        min(x.date) AS mindate,
        max(x.date) AS maxdate,
        sum(x.spent) AS spent_total_checkbooknyc
    FROM (
        SELECT
            trim(left(capital_project, 12)) AS maprojid,
            issue_date::text AS date,
            check_amount::double precision AS spent
        FROM nycoc_checkbook
        UNION ALL
        SELECT
            maprojid,
            to_date(plancommdate, 'MM/YY')::text AS date,
            0 AS spent
        FROM ccp_commitments
    ) AS x
    GROUP BY x.maprojid
) AS c ON a.maprojid = c.maprojid
LEFT JOIN cpdb_dcpattributes AS d ON a.maprojid = d.maprojid
LEFT JOIN cpdb_budget_data_wide AS e ON a.maprojid = e.maprojid;

CREATE VIEW cpdb_projects AS
SELECT
    ccpversion,
    maprojid,
    magencyacro,
    magency,
    magencyname,
    description,
    projectid,
    mindate,
    maxdate,
    typecategory,
    plannedcommit_ccnonexempt,
    plannedcommit_ccexempt,
    plannedcommit_citycost,
    plannedcommit_nccstate,
    plannedcommit_nccfederal,
    plannedcommit_nccother,
    plannedcommit_noncitycost,
    plannedcommit_total,
    adopt_ccnonexempt,
    adopt_ccexempt,
    adopt_citycost,
    adopt_nccstate,
    adopt_nccfederal,
    adopt_nccother,
    adopt_noncitycost,
    adopt_total,
    allocate_ccnonexempt,
    allocate_ccexempt,
    allocate_citycost,
    allocate_nccstate,
    allocate_nccfederal,
    allocate_nccother,
    allocate_noncitycost,
    allocate_total,
    commit_ccnonexempt,
    commit_ccexempt,
    commit_citycost,
    commit_nccstate,
    commit_nccfederal,
    commit_nccother,
    commit_noncitycost,
    commit_total,
    spent_ccnonexempt,
    spent_ccexempt,
    spent_citycost,
    spent_nccstate,
    spent_nccfederal,
    spent_nccother,
    spent_noncitycost,
    spent_total,
    spent_total_checkbooknyc
FROM cpdb_projects_geom;

CREATE VIEW cpdb_projects_shp AS
SELECT
    ccpversion,
    maprojid,
    magencyacro AS magenacro,
    magency,
    magencyname AS magenname,
    description AS descript,
    projectid,
    mindate,
    maxdate,
    typecategory AS typecat,
    plannedcommit_ccnonexempt AS pcccnonex,
    plannedcommit_ccexempt AS pcccex,
    plannedcommit_citycost AS pccc,
    plannedcommit_nccstate AS pcnccstate,
    plannedcommit_nccfederal AS pcnccfed,
    plannedcommit_nccother AS pcnccother,
    plannedcommit_noncitycost AS pcncc,
    plannedcommit_total AS pctotal,
    adopt_ccnonexempt AS adccnonex,
    adopt_ccexempt AS adccex,
    adopt_citycost AS adcc,
    adopt_nccstate AS adnccstate,
    adopt_nccfederal AS adnccfed,
    adopt_nccother AS adnccother,
    adopt_noncitycost AS adncc,
    adopt_total AS adtotal,
    allocate_ccnonexempt AS alccnonex,
    allocate_ccexempt AS alccex,
    allocate_citycost AS alcc,
    allocate_nccstate AS alnccstate,
    allocate_nccfederal AS alnccfed,
    allocate_nccother AS alnccother,
    allocate_noncitycost AS alncc,
    allocate_total AS altotal,
    commit_ccnonexempt AS coccnonex,
    commit_ccexempt AS coccex,
    commit_citycost AS cocc,
    commit_nccstate AS conccstate,
    commit_nccfederal AS conccfed,
    commit_nccother AS conccother,
    commit_noncitycost AS concc,
    commit_total AS cototal,
    spent_ccnonexempt AS spccnonex,
    spent_ccexempt AS spccex,
    spent_citycost AS spcc,
    spent_nccstate AS spnccstate,
    spent_nccfederal AS spnccfed,
    spent_nccother AS spnccother,
    spent_noncitycost AS spncc,
    spent_total AS sptotal,
    spent_total_checkbooknyc AS sptotalcb,
    geom
FROM cpdb_projects_geom;
