DROP TABLE IF EXISTS _init_hpd_historical_units_by_building;
SELECT
    ogc_fid,
    project_id,
    project_name,
    NULL AS project_start_date,
    NULL AS project_completion_date,
    building_id,
    house_number AS number,
    street_name AS street,
    boro_short_name AS borough,
    NULL AS postcode,
    bbl,
    NULL AS bin,
    NULL AS community_board,
    NULL AS council_district,
    NULL AS census_tract,
    NULL AS nta___neighborhood_tabulation_area,
    NULL AS latitude,
    NULL AS longitude,
    NULL AS "latitude_(internal)",
    NULL AS "longitude_(internal)",
    NULL AS building_completion_date,
    reporting_construction_type,
    affordable_units AS extended_affordability_only,
    NULL AS prevailing_wage_status,
    NULL AS extremely_low_income_units,
    NULL AS very_low_income_units,
    NULL AS low_income_units,
    NULL AS moderate_income_units,
    NULL AS middle_income_units,
    NULL AS other_income_units,
    NULL AS studio_units,
    NULL AS 1_br_units,
    NULL AS 2_br_units,
    NULL AS 3_br_units,
    NULL AS 4_br_units,
    NULL AS 5_br_units,
    NULL AS "6_br+_units",
    NULL AS unknown_br_units,
    NULL AS counted_rental_units,
    NULL AS counted_homeownership_units,
    NULL AS all_counted_units,
    total_units,
    data_library_version
INTO _init_hpd_historical_units_by_building
FROM hpd_historical_units_by_building;
