DROP TABLE IF EXISTS final_devdb;
SELECT DISTINCT ON (mid_devdb.job_number)
    mid_devdb.job_number,
    mid_devdb.job_type,
    mid_devdb.resid_flag,
    mid_devdb.nonres_flag,
    mid_devdb.job_inactive,
    mid_devdb.job_status,
    mid_devdb.complete_year,
    mid_devdb.complete_qrtr,
    mid_devdb.permit_year,
    mid_devdb.permit_qrtr,
    mid_devdb.classa_init,
    mid_devdb.classa_prop,
    mid_devdb.classa_net,
    devdb_hny_lookup.classa_hnyaff,
    mid_devdb.hotel_init,
    mid_devdb.hotel_prop,
    mid_devdb.otherb_init,
    mid_devdb.otherb_prop,
    mid_devdb.co_latest_units AS units_co,
    coalesce(mid_devdb.geo_boro, mid_devdb.boro) AS boro,
    coalesce(mid_devdb.geo_bin, mid_devdb.bin) AS bin,
    coalesce(mid_devdb.geo_bbl, mid_devdb.bbl) AS bbl,
    regexp_replace(
        coalesce(mid_devdb.geo_address_numbr, mid_devdb.address_numbr), '[\s]{2,}', ' ', 'g'
    ) AS address_numbr,
    regexp_replace(
        coalesce(mid_devdb.geo_address_street, mid_devdb.address_street), '[\s]{2,}', ' ', 'g'
    ) AS address_st,
    regexp_replace(
        coalesce(mid_devdb.geo_address_numbr, mid_devdb.address_numbr)
        || ' ' || coalesce(mid_devdb.geo_address_street, mid_devdb.address_street), '[\s]{2,}', ' ', 'g'
    ) AS address,
    mid_devdb.occ_initial,
    mid_devdb.occ_proposed,
    mid_devdb.bldg_class,
    mid_devdb.job_desc,
    mid_devdb.desc_other,
    mid_devdb.date_filed,
    mid_devdb.date_statusd,
    mid_devdb.date_statusp,
    mid_devdb.date_permittd,
    mid_devdb.date_statusr,
    mid_devdb.date_statusx,
    mid_devdb.date_lastupdt,
    mid_devdb.date_complete,
    mid_devdb.zoningdist1,
    mid_devdb.zoningdist2,
    mid_devdb.zoningdist3,
    mid_devdb.specialdist1,
    mid_devdb.specialdist2,
    mid_devdb.landmark,
    mid_devdb.zsf_init,
    mid_devdb.zsf_prop,
    mid_devdb.zug_init,
    mid_devdb.zug_prop,
    mid_devdb.zsfr_prop,
    mid_devdb.zsfc_prop,
    mid_devdb.zsfcf_prop,
    mid_devdb.zsfm_prop,
    mid_devdb.prkng_init,
    mid_devdb.prkng_prop,
    mid_devdb.stories_init,
    mid_devdb.stories_prop,
    mid_devdb.height_init,
    mid_devdb.height_prop,
    mid_devdb.constructnsf,
    mid_devdb.enlargement,
    mid_devdb.enlargementsf,
    mid_devdb.costestimate,
    mid_devdb.loftboardcert,
    mid_devdb.edesignation,
    mid_devdb.curbcut,
    mid_devdb.tracthomes,
    mid_devdb.ownership,
    mid_devdb.owner_name,
    mid_devdb.owner_biznm,
    mid_devdb.owner_address,
    mid_devdb.owner_zipcode,
    mid_devdb.owner_phone,
    pluto_devdb.pluto_unitres,
    pluto_devdb.pluto_bldgsf,
    pluto_devdb.pluto_comsf,
    pluto_devdb.pluto_offcsf,
    pluto_devdb.pluto_retlsf,
    pluto_devdb.pluto_ressf,
    pluto_devdb.pluto_yrbuilt,
    pluto_devdb.pluto_yralt1,
    pluto_devdb.pluto_yralt2,
    pluto_devdb.pluto_histdst,
    pluto_devdb.pluto_landmk,
    pluto_devdb.pluto_bldgcls,
    pluto_devdb.pluto_landuse,
    pluto_devdb.pluto_owner,
    pluto_devdb.pluto_owntype,
    pluto_devdb.pluto_condo,
    pluto_devdb.pluto_bldgs,
    pluto_devdb.pluto_floors,
    pluto_devdb.pluto_version,
    mid_devdb.geo_cb2020 AS cenblock2020,
    mid_devdb.geo_ct2020 AS centract2020,
    mid_devdb.bctcb2020,
    mid_devdb.bct2020,
    mid_devdb.geo_nta2020 AS nta2020,
    mid_devdb.geo_ntaname2020 AS ntaname2020,
    mid_devdb.geo_cdta2020 AS cdta2020,
    mid_devdb.geo_cdtaname2020 AS cdtaname2020,
    mid_devdb.geo_cd AS comunitydist,
    mid_devdb.geo_council AS councildist,
    mid_devdb.geo_schoolsubdist AS schoolsubdist,
    mid_devdb.geo_csd AS schoolcommnty,
    mid_devdb.geo_schoolelmntry AS schoolelmntry,
    mid_devdb.geo_schoolmiddle AS schoolmiddle,
    mid_devdb.geo_firecompany AS firecompany,
    mid_devdb.geo_firebattalion AS firebattalion,
    mid_devdb.geo_firedivision AS firedivision,
    mid_devdb.geo_policeprct AS policeprecnct,
    --    depdrainarea,
    --    deppumpstatn,
    pluto_devdb.pluto_firm07,
    pluto_devdb.pluto_pfirm15,
    mid_devdb.latitude,
    mid_devdb.longitude,
    mid_devdb.datasource,
    mid_devdb.geomsource,
    corr_lists.dcpeditfields,
    devdb_hny_lookup.hny_id,
    devdb_hny_lookup.hny_jobrelate,
    :'VERSION' AS version
INTO final_devdb
FROM mid_devdb
LEFT JOIN devdb_hny_lookup ON mid_devdb.job_number = devdb_hny_lookup.job_number
LEFT JOIN pluto_devdb ON mid_devdb.job_number = pluto_devdb.job_number
LEFT JOIN (
    SELECT
        job_number,
        string_agg(field, '/') AS dcpeditfields
    FROM corrections_applied
    GROUP BY job_number
) AS corr_lists ON mid_devdb.job_number = corr_lists.job_number;
