name: LION
product: lion
version: 25c_fixed

inputs:
  dataset_defaults:
    destination: postgres
    file_type: gdb
    source: edm.recipes.raw_datasets
  datasets:
  # segment source layers - backbone
  - name: dcp_cscl_gdb
    custom:
      filename: ETL Working GDB.gdb.zip
      layer_name: Centerline

  missing_versions_strategy: find_latest # TODO - they should all match
