name: EDDE - 🏗️ Build
run-name: "EDDE - 🏗️ Build: ${{ inputs.build_name }}"

on:
  workflow_dispatch:
    inputs:
      build_name:
        type: string
        required: true
      image_tag:
        type: string
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_NAME: ${{ inputs.build_name }}
  RECIPES_BUCKET: 'edm-recipes'
  PUBLISHING_BUCKET: 'edm-publishing'
  DCPY_LIFECYCLE_DATA_DIR: ${{ github.workspace }}/.lifecycle

jobs:
  build:
    name: "Build EDDE"
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: products/edde
    container:
      image: nycplanning/dev:${{ inputs.image_tag || 'latest' }}
    steps:
      - uses: actions/checkout@v4

      - name: Load Secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          AWS_S3_ENDPOINT: "op://Data Engineering/DO_keys/AWS_S3_ENDPOINT"
          AWS_SECRET_ACCESS_KEY: "op://Data Engineering/DO_keys/AWS_SECRET_ACCESS_KEY"
          AWS_ACCESS_KEY_ID: "op://Data Engineering/DO_keys/AWS_ACCESS_KEY_ID"

      - name: Finish container setup ...
        working-directory: ./
        run: ./bash/docker_container_setup.sh

      - name: Set build directory
        run: |
          BUILD_DIR=$(python3 -c "from dcpy.lifecycle.config import get_build_dir; print(get_build_dir('edde', '${BUILD_NAME}'))")
          mkdir -p "$BUILD_DIR"
          echo "BUILD_ENV_OUTPUT_DIR=$BUILD_DIR" >> "$GITHUB_ENV"

      - name: Plan build
        run: python3 -m dcpy.lifecycle.builds.plan recipe --recipe-path recipe.yml --output-path "$BUILD_ENV_OUTPUT_DIR/recipe.lock.yml"

      - name: Dataloading
        run: python3 -m dcpy lifecycle builds load load --recipe-path "$BUILD_ENV_OUTPUT_DIR/recipe.lock.yml"

      - name: Build (build, data_checks, qa, package)
        run: python3 -m dcpy lifecycle builds build run --recipe-path "$BUILD_ENV_OUTPUT_DIR/recipe.lock.yml" --build-dir "$BUILD_ENV_OUTPUT_DIR"

      - name: Upload
        run: python3 -m dcpy lifecycle builds build upload "$BUILD_ENV_OUTPUT_DIR" --recipe-path "$BUILD_ENV_OUTPUT_DIR/recipe.lock.yml"
