name: Deploy DE Tools to DO

on:
  workflow_dispatch:
    inputs:
      data_engineering_branch:
        description: 'Data Engineering branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      DATA_ENGINEERING_BRANCH: ${{ github.event.inputs.data_engineering_branch || 'main' }}
      QA_DROPLET_SSH_PRIVATE_KEY: ${{ secrets.QA_DROPLET_SSH_PRIVATE_KEY }}
      QA_DROPLET_SSH_HOST: ${{ secrets.QA_DROPLET_SSH_HOST }}

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$QA_DROPLET_SSH_PRIVATE_KEY" > ~/.ssh/droplet.key
          chmod 400 ~/.ssh/droplet.key
          cat >> ~/.ssh/config <<EOF
          Host droplet
            HostName $QA_DROPLET_SSH_HOST
            User root
            IdentityFile ~/.ssh/droplet.key
            StrictHostKeyChecking no
            ConnectTimeout 600
          EOF

      - name: Pull latest data-engineering code on droplet
        run: |
          ssh droplet "\
            cd /root/data-engineering && \
            git fetch origin $DATA_ENGINEERING_BRANCH --depth 1 && \
            git reset --hard FETCH_HEAD"

      - name: Deploy services
        run: |
          ssh droplet "\
            cd /root/data-engineering/apps && \
            export OP_SERVICE_ACCOUNT_TOKEN='${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}' && \
            op run --env-file=env.1pw -- ./scripts/deploy.sh"

      - name: Restart nginx
        run: |
          ssh droplet "\
            cd /root/data-engineering/apps && \
            # sleep for one minute to allow services to start before nginx tries to connect to them
            sleep 60 && \
            docker compose restart nginx"

      - name: Verify deployment
        run: |
          ssh droplet "\
            cd /root/data-engineering/apps && \
            docker compose ps && \
            docker compose logs --tail=50"
